In [6]:
%pip install polars
import polars as pl
from pathlib import Path
%pip install fastexcel

Requirement already satisfied: polars in /opt/miniconda3/lib/python3.14/site-packages (1.44.2)
Requirement already satisfied: polars-runtime-32==1.44.2 in /opt/miniconda3/lib/python3.14/site-packages (from polars) (1.44.2)
Note: you may need to restart the kernel to use updated packages.
Collecting fastexcel
  Downloading fastexcel-0.21.0-cp310-abi3-macosx_11_0_arm64.whl.metadata (7.2 kB)
Downloading fastexcel-0.21.0-cp310-abi3-macosx_11_0_arm64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 17.2 MB/s  0:00:002.8 MB/s eta 0:00:01
Installing collected packages: fastexcel
Successfully installed fastexcel-0.21.0
Note: you may need to restart the kernel to use updated packages.

In [7]:
data_dir = Path.cwd().parent / "assets"
year_2025_data = data_dir / "TTC Subway Delay Data since 2025.csv"
year_2024_data = data_dir / "ttc-subway-delay-data-2024.xlsx"

In [9]:
df_2025 = pl.read_csv(year_2025_data)
df_2025.glimpse()

Rows: 40656
Columns: 11
$ _id       <i64> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
$ Date      <str> '2025-01-01', '2025-01-01', '2025-01-01', '2025-01-01', '2025-01-01', '2025-01-01', '2025-01-01', '2025-01-01', '2025-01-01', '2025-01-01'
$ Time      <str> '02:10', '02:30', '02:32', '02:58', '02:58', '07:59', '08:13', '08:15', '09:14', '09:22'
$ Day       <str> 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday'
$ Station   <str> 'BATHURST STATION', 'DUNDAS STATION', 'BROADVIEW STATION', 'KEELE STATION', 'COXWELL STATION', 'DONLANDS STATION', 'BLOOR STATION', 'BLOOR STATION', 'FINCH STATION', 'BATHURST STATION'
$ Code      <str> 'MUSAN', 'MUIRS', 'PUMST', 'EUSC', 'SUAE', 'TUNOA', 'PUTR', 'PUTR', 'SUDP', 'SUUT'
$ Min Delay <i64> 5, 0, 0, 0, 0, 5, 9, 5, 0, 0
$ Min Gap   <i64> 9, 0, 0, 0, 0, 10, 0, 0, 0, 0
$ Bound     <str> 'E', null, 'E', 'W', null, 'W', 'S', 'N', 'S', 'E'
$ Line      <str> 'BD', 'YU', 'BD', 'BD', 'BD', 'BD', 'YU', 'YU', 'YU', 'BD'
$ Vehicle   <i64> 5227, 0, 0, 5293, 0, 5000, 5836, 5706, 5596, 5312

In [10]:
df_2025 = df_2025.with_columns(
    pl.col("Date").str.to_date("%Y-%m-%d"),
    pl.col("Time").str.to_time("%H:%M")
)
df_2025.glimpse()

Rows: 40656
Columns: 11
$ _id        <i64> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
$ Date      <date> 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01
$ Time      <time> 02:10:00, 02:30:00, 02:32:00, 02:58:00, 02:58:00, 07:59:00, 08:13:00, 08:15:00, 09:14:00, 09:22:00
$ Day        <str> 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday'
$ Station    <str> 'BATHURST STATION', 'DUNDAS STATION', 'BROADVIEW STATION', 'KEELE STATION', 'COXWELL STATION', 'DONLANDS STATION', 'BLOOR STATION', 'BLOOR STATION', 'FINCH STATION', 'BATHURST STATION'
$ Code       <str> 'MUSAN', 'MUIRS', 'PUMST', 'EUSC', 'SUAE', 'TUNOA', 'PUTR', 'PUTR', 'SUDP', 'SUUT'
$ Min Delay  <i64> 5, 0, 0, 0, 0, 5, 9, 5, 0, 0
$ Min Gap    <i64> 9, 0, 0, 0, 0, 10, 0, 0, 0, 0
$ Bound      <str> 'E', null, 'E', 'W', null, 'W', 'S', 'N', 'S', 'E'
$ Line       <str> 'BD', 'YU', 'BD', 'BD', 'BD', 'BD', 'YU', 'YU', 'YU', 'BD'
$ Vehicle    <i64> 5227, 0, 0, 5293, 0, 5000, 5836, 5706, 5596, 5312

In [12]:
df_2025 = df_2025.drop("_id")
df_2025.glimpse()

Rows: 40656
Columns: 10
$ Date      <date> 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01
$ Time      <time> 02:10:00, 02:30:00, 02:32:00, 02:58:00, 02:58:00, 07:59:00, 08:13:00, 08:15:00, 09:14:00, 09:22:00
$ Day        <str> 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday'
$ Station    <str> 'BATHURST STATION', 'DUNDAS STATION', 'BROADVIEW STATION', 'KEELE STATION', 'COXWELL STATION', 'DONLANDS STATION', 'BLOOR STATION', 'BLOOR STATION', 'FINCH STATION', 'BATHURST STATION'
$ Code       <str> 'MUSAN', 'MUIRS', 'PUMST', 'EUSC', 'SUAE', 'TUNOA', 'PUTR', 'PUTR', 'SUDP', 'SUUT'
$ Min Delay  <i64> 5, 0, 0, 0, 0, 5, 9, 5, 0, 0
$ Min Gap    <i64> 9, 0, 0, 0, 0, 10, 0, 0, 0, 0
$ Bound      <str> 'E', null, 'E', 'W', null, 'W', 'S', 'N', 'S', 'E'
$ Line       <str> 'BD', 'YU', 'BD', 'BD', 'BD', 'BD', 'YU', 'YU', 'YU', 'BD'
$ Vehicle    <i64> 5227, 0, 0, 5293, 0, 5000, 5836, 5706, 5596, 5312

In [11]:
df_2024 = pl.read_excel(year_2024_data)

Rows: 26467
Columns: 10
$ Date      <date> 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01
$ Time       <str> '02:00', '02:00', '02:08', '02:13', '02:22', '02:25', '02:25', '02:27', '02:28', '02:30'
$ Day        <str> 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday'
$ Station    <str> 'SHEPPARD STATION', 'DUNDAS STATION', 'DUNDAS STATION', 'KENNEDY BD STATION', 'BLOOR STATION', 'ST CLAIR STATION', 'BLOOR STATION', 'WOODBINE STATION', 'FINCH STATION', 'DAVISVILLE STATION'
$ Code       <str> 'MUI', 'MUIS', 'MUPAA', 'PUTDN', 'MUPAA', 'MUPAA', 'MUIRS', 'EUDO', 'MUIRS', 'MUI'
$ Min Delay  <i64> 0, 0, 4, 10, 4, 3, 0, 7, 0, 13
$ Min Gap    <i64> 0, 0, 10, 16, 10, 9, 0, 13, 0, 19
$ Bound      <str> 'N', 'N', 'N', 'E', 'N', 'N', 'S', 'E', 'S', 'N'
$ Line       <str> 'YU', 'YU', 'YU', 'BD', 'YU', 'YU', 'YU', 'BD', 'YU', 'YU'
$ Vehicle    <i64> 5491, 0, 6051, 5284, 5986, 6051, 0, 5077, 5561, 6051

/var/folders/ch/33mzvf3519l1kk_ktmcysmc80000gn/T/ipykernel_81715/3704599578.py:1: FutureWarning: from_arrow(<ArrowStreamExportable>) will return a Series instead of a DataFrame in 2.0. To avoid this warning, pass the ArrowStreamExportable to either `pl.DataFrame` or `pl.Series` instead based on your desired output type.
  df_2024 = pl.read_excel(year_2024_data)

In [16]:
df_2024.glimpse()

Rows: 26467
Columns: 10
$ Date      <date> 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01
$ Time      <time> 02:00:00, 02:00:00, 02:08:00, 02:13:00, 02:22:00, 02:25:00, 02:25:00, 02:27:00, 02:28:00, 02:30:00
$ Day        <str> 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday'
$ Station    <str> 'SHEPPARD STATION', 'DUNDAS STATION', 'DUNDAS STATION', 'KENNEDY BD STATION', 'BLOOR STATION', 'ST CLAIR STATION', 'BLOOR STATION', 'WOODBINE STATION', 'FINCH STATION', 'DAVISVILLE STATION'
$ Code       <str> 'MUI', 'MUIS', 'MUPAA', 'PUTDN', 'MUPAA', 'MUPAA', 'MUIRS', 'EUDO', 'MUIRS', 'MUI'
$ Min Delay  <i64> 0, 0, 4, 10, 4, 3, 0, 7, 0, 13
$ Min Gap    <i64> 0, 0, 10, 16, 10, 9, 0, 13, 0, 19
$ Bound      <str> 'N', 'N', 'N', 'E', 'N', 'N', 'S', 'E', 'S', 'N'
$ Line       <str> 'YU', 'YU', 'YU', 'BD', 'YU', 'YU', 'YU', 'BD', 'YU', 'YU'
$ Vehicle    <i64> 5491, 0, 6051, 5284, 5986, 6051, 0, 5077, 5561, 6051

In [17]:
df_2024.glimpse(), df_2025.glimpse()

Rows: 26467
Columns: 10
$ Date      <date> 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01, 2024-01-01
$ Time      <time> 02:00:00, 02:00:00, 02:08:00, 02:13:00, 02:22:00, 02:25:00, 02:25:00, 02:27:00, 02:28:00, 02:30:00
$ Day        <str> 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday', 'Monday'
$ Station    <str> 'SHEPPARD STATION', 'DUNDAS STATION', 'DUNDAS STATION', 'KENNEDY BD STATION', 'BLOOR STATION', 'ST CLAIR STATION', 'BLOOR STATION', 'WOODBINE STATION', 'FINCH STATION', 'DAVISVILLE STATION'
$ Code       <str> 'MUI', 'MUIS', 'MUPAA', 'PUTDN', 'MUPAA', 'MUPAA', 'MUIRS', 'EUDO', 'MUIRS', 'MUI'
$ Min Delay  <i64> 0, 0, 4, 10, 4, 3, 0, 7, 0, 13
$ Min Gap    <i64> 0, 0, 10, 16, 10, 9, 0, 13, 0, 19
$ Bound      <str> 'N', 'N', 'N', 'E', 'N', 'N', 'S', 'E', 'S', 'N'
$ Line       <str> 'YU', 'YU', 'YU', 'BD', 'YU', 'YU', 'YU', 'BD', 'YU', 'YU'
$ Vehicle    <i64> 5491, 0, 6051, 5284, 5986, 6051, 0, 5077, 5561, 6051

Rows: 40656
Columns: 10
$ Date      <date> 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01, 2025-01-01
$ Time      <time> 02:10:00, 02:30:00, 02:32:00, 02:58:00, 02:58:00, 07:59:00, 08:13:00, 08:15:00, 09:14:00, 09:22:00
$ Day        <str> 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday', 'Wednesday'
$ Station    <str> 'BATHURST STATION', 'DUNDAS STATION', 'BROADVIEW STATION', 'KEELE STATION', 'COXWELL STATION', 'DONLANDS STATION', 'BLOOR STATION', 'BLOOR STATION', 'FINCH STATION', 'BATHURST STATION'
$ Code       <str> 'MUSAN', 'MUIRS', 'PUMST', 'EUSC', 'SUAE', 'TUNOA', 'PUTR', 'PUTR', 'SUDP', 'SUUT'
$ Min Delay  <i64> 5, 0, 0, 0, 0, 5, 9, 5, 0, 0
$ Min Gap    <i64> 9, 0, 0, 0, 0, 10, 0, 0, 0, 0
$ Bound      <str> 'E', null, 'E', 'W', null, 'W', 'S', 'N', 'S', 'E'
$ Line       <str> 'BD', 'YU', 'BD', 'BD', 'BD', 'BD', 'YU', 'YU', 'YU', 'BD'
$ Vehicle    <i64> 5227, 0, 0, 5293, 0, 5000, 5836, 5706, 5596, 5312

(None, None)

In [18]:
df_since_24 = pl.concat([df_2024, df_2025])
df_since_24

shape: (67_123, 10)
┌────────────┬──────────┬─────────┬────────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time     ┆ Day     ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---      ┆ ---     ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ time     ┆ str     ┆ str                    ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪══════════╪═════════╪════════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2024-01-01 ┆ 02:00:00 ┆ Monday  ┆ SHEPPARD STATION       ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5491    │
│ 2024-01-01 ┆ 02:00:00 ┆ Monday  ┆ DUNDAS STATION         ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 0       │
│ 2024-01-01 ┆ 02:08:00 ┆ Monday  ┆ DUNDAS STATION         ┆ … ┆ 10      ┆ N     ┆ YU   ┆ 6051    │
│ 2024-01-01 ┆ 02:13:00 ┆ Monday  ┆ KENNEDY BD STATION     ┆ … ┆ 16      ┆ E     ┆ BD   ┆ 5284    │
│ 2024-01-01 ┆ 02:22:00 ┆ Monday  ┆ BLOOR STATION          ┆ … ┆ 10      ┆ N     ┆ YU   ┆ 5986    │
│ …          ┆ …        ┆ …       ┆ …                      ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2026-06-30 ┆ 01:37:00 ┆ Tuesday ┆ KENNEDY BD STATION     ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 0       │
│ 2026-06-30 ┆ 17:57:00 ┆ Tuesday ┆ SHEPPARD-YONGE STATION ┆ … ┆ 0       ┆ W     ┆ SHP  ┆ 6191    │
│ 2026-06-30 ┆ 18:53:00 ┆ Tuesday ┆ DON MILLS STATION      ┆ … ┆ 0       ┆ null  ┆ SHP  ┆ 0       │
│ 2026-06-30 ┆ 21:04:00 ┆ Tuesday ┆ SHEPPARD-YONGE STATION ┆ … ┆ 0       ┆ E     ┆ SHP  ┆ 6161    │
│ 2026-06-30 ┆ 21:26:00 ┆ Tuesday ┆ SHEPPARD-YONGE STATION ┆ … ┆ 9       ┆ W     ┆ SHP  ┆ 6176    │
└────────────┴──────────┴─────────┴────────────────────────┴───┴─────────┴───────┴──────┴─────────┘

In [19]:
df_2023_path = data_dir / "ttc-subway-delay-data-2023.xlsx"
df_2023 = pl.read_excel(df_2023_path)
df_2023

/var/folders/ch/33mzvf3519l1kk_ktmcysmc80000gn/T/ipykernel_81715/3809606928.py:2: FutureWarning: from_arrow(<ArrowStreamExportable>) will return a Series instead of a DataFrame in 2.0. To avoid this warning, pass the ArrowStreamExportable to either `pl.DataFrame` or `pl.Series` instead based on your desired output type.
  df_2023 = pl.read_excel(df_2023_path)

shape: (22_949, 10)
┌────────────┬───────┬────────┬────────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time  ┆ Day    ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---   ┆ ---    ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ str   ┆ str    ┆ str                    ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪═══════╪════════╪════════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2023-01-01 ┆ 02:22 ┆ Sunday ┆ MUSEUM STATION         ┆ … ┆ 9       ┆ S     ┆ YU   ┆ 5931    │
│ 2023-01-01 ┆ 02:30 ┆ Sunday ┆ KIPLING STATION        ┆ … ┆ 0       ┆ E     ┆ BD   ┆ 5341    │
│ 2023-01-01 ┆ 02:33 ┆ Sunday ┆ WARDEN STATION         ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 0       │
│ 2023-01-01 ┆ 03:17 ┆ Sunday ┆ KEELE STATION          ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ 2023-01-01 ┆ 07:16 ┆ Sunday ┆ BATHURST STATION       ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ …          ┆ …     ┆ …      ┆ …                      ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2023-12-31 ┆ 12:25 ┆ Sunday ┆ SHEPPARD-YONGE STATION ┆ … ┆ 14      ┆ W     ┆ SHP  ┆ 6196    │
│ 2023-12-31 ┆ 13:53 ┆ Sunday ┆ BAYVIEW STATION        ┆ … ┆ 0       ┆ E     ┆ SHP  ┆ 6191    │
│ 2023-12-31 ┆ 14:57 ┆ Sunday ┆ SHEPPARD-YONGE STATION ┆ … ┆ 58      ┆ W     ┆ SHP  ┆ 6171    │
│ 2023-12-31 ┆ 15:15 ┆ Sunday ┆ BAYVIEW STATION        ┆ … ┆ 14      ┆ E     ┆ SHP  ┆ 6141    │
│ 2023-12-31 ┆ 20:52 ┆ Sunday ┆ DON MILLS STATION      ┆ … ┆ 0       ┆ null  ┆ SHP  ┆ 0       │
└────────────┴───────┴────────┴────────────────────────┴───┴─────────┴───────┴──────┴─────────┘

In [20]:
df_2023 = df_2023.with_columns(
    pl.col("Time").str.to_time("%H:%M")
)
df_2023

shape: (22_949, 10)
┌────────────┬──────────┬────────┬────────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time     ┆ Day    ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---      ┆ ---    ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ time     ┆ str    ┆ str                    ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪══════════╪════════╪════════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2023-01-01 ┆ 02:22:00 ┆ Sunday ┆ MUSEUM STATION         ┆ … ┆ 9       ┆ S     ┆ YU   ┆ 5931    │
│ 2023-01-01 ┆ 02:30:00 ┆ Sunday ┆ KIPLING STATION        ┆ … ┆ 0       ┆ E     ┆ BD   ┆ 5341    │
│ 2023-01-01 ┆ 02:33:00 ┆ Sunday ┆ WARDEN STATION         ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 0       │
│ 2023-01-01 ┆ 03:17:00 ┆ Sunday ┆ KEELE STATION          ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ 2023-01-01 ┆ 07:16:00 ┆ Sunday ┆ BATHURST STATION       ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ …          ┆ …        ┆ …      ┆ …                      ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2023-12-31 ┆ 12:25:00 ┆ Sunday ┆ SHEPPARD-YONGE STATION ┆ … ┆ 14      ┆ W     ┆ SHP  ┆ 6196    │
│ 2023-12-31 ┆ 13:53:00 ┆ Sunday ┆ BAYVIEW STATION        ┆ … ┆ 0       ┆ E     ┆ SHP  ┆ 6191    │
│ 2023-12-31 ┆ 14:57:00 ┆ Sunday ┆ SHEPPARD-YONGE STATION ┆ … ┆ 58      ┆ W     ┆ SHP  ┆ 6171    │
│ 2023-12-31 ┆ 15:15:00 ┆ Sunday ┆ BAYVIEW STATION        ┆ … ┆ 14      ┆ E     ┆ SHP  ┆ 6141    │
│ 2023-12-31 ┆ 20:52:00 ┆ Sunday ┆ DON MILLS STATION      ┆ … ┆ 0       ┆ null  ┆ SHP  ┆ 0       │
└────────────┴──────────┴────────┴────────────────────────┴───┴─────────┴───────┴──────┴─────────┘

In [21]:
df_since_23 = pl.concat([df_2023, df_since_24])
df_since_23

shape: (90_072, 10)
┌────────────┬──────────┬─────────┬────────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time     ┆ Day     ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---      ┆ ---     ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ time     ┆ str     ┆ str                    ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪══════════╪═════════╪════════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2023-01-01 ┆ 02:22:00 ┆ Sunday  ┆ MUSEUM STATION         ┆ … ┆ 9       ┆ S     ┆ YU   ┆ 5931    │
│ 2023-01-01 ┆ 02:30:00 ┆ Sunday  ┆ KIPLING STATION        ┆ … ┆ 0       ┆ E     ┆ BD   ┆ 5341    │
│ 2023-01-01 ┆ 02:33:00 ┆ Sunday  ┆ WARDEN STATION         ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 0       │
│ 2023-01-01 ┆ 03:17:00 ┆ Sunday  ┆ KEELE STATION          ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ 2023-01-01 ┆ 07:16:00 ┆ Sunday  ┆ BATHURST STATION       ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ …          ┆ …        ┆ …       ┆ …                      ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2026-06-30 ┆ 01:37:00 ┆ Tuesday ┆ KENNEDY BD STATION     ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 0       │
│ 2026-06-30 ┆ 17:57:00 ┆ Tuesday ┆ SHEPPARD-YONGE STATION ┆ … ┆ 0       ┆ W     ┆ SHP  ┆ 6191    │
│ 2026-06-30 ┆ 18:53:00 ┆ Tuesday ┆ DON MILLS STATION      ┆ … ┆ 0       ┆ null  ┆ SHP  ┆ 0       │
│ 2026-06-30 ┆ 21:04:00 ┆ Tuesday ┆ SHEPPARD-YONGE STATION ┆ … ┆ 0       ┆ E     ┆ SHP  ┆ 6161    │
│ 2026-06-30 ┆ 21:26:00 ┆ Tuesday ┆ SHEPPARD-YONGE STATION ┆ … ┆ 9       ┆ W     ┆ SHP  ┆ 6176    │
└────────────┴──────────┴─────────┴────────────────────────┴───┴─────────┴───────┴──────┴─────────┘

In [22]:
df_2022_path = data_dir / "ttc-subway-delay-data-2022.xlsx"
df_2022 = pl.read_excel(df_2022_path)
df_2022

/var/folders/ch/33mzvf3519l1kk_ktmcysmc80000gn/T/ipykernel_81715/3335129940.py:2: FutureWarning: from_arrow(<ArrowStreamExportable>) will return a Series instead of a DataFrame in 2.0. To avoid this warning, pass the ArrowStreamExportable to either `pl.DataFrame` or `pl.Series` instead based on your desired output type.
  df_2022 = pl.read_excel(df_2022_path)

shape: (19_895, 10)
┌────────────┬───────┬──────────┬────────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time  ┆ Day      ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---   ┆ ---      ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ str   ┆ str      ┆ str                    ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪═══════╪══════════╪════════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2022-01-01 ┆ 15:59 ┆ Saturday ┆ LAWRENCE EAST STATION  ┆ … ┆ 0       ┆ N     ┆ SRT  ┆ 3023    │
│ 2022-01-01 ┆ 02:23 ┆ Saturday ┆ SPADINA BD STATION     ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ 2022-01-01 ┆ 22:00 ┆ Saturday ┆ KENNEDY SRT STATION TO ┆ … ┆ 0       ┆ null  ┆ SRT  ┆ 0       │
│ 2022-01-01 ┆ 02:28 ┆ Saturday ┆ VAUGHAN MC STATION     ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2022-01-01 ┆ 02:34 ┆ Saturday ┆ EGLINTON STATION       ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 5981    │
│ …          ┆ …     ┆ …        ┆ …                      ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2022-12-31 ┆ 01:20 ┆ Saturday ┆ BAY STATION            ┆ … ┆ 22      ┆ E     ┆ BD   ┆ 5089    │
│ 2022-12-31 ┆ 01:31 ┆ Saturday ┆ SHEPPARD WEST STATION  ┆ … ┆ 29      ┆ N     ┆ YU   ┆ 5656    │
│ 2022-12-31 ┆ 01:33 ┆ Saturday ┆ BAY STATION            ┆ … ┆ 0       ┆ E     ┆ BD   ┆ 5313    │
│ 2022-12-31 ┆ 01:49 ┆ Saturday ┆ YONGE BD STATION       ┆ … ┆ 9       ┆ E     ┆ BD   ┆ 5211    │
│ 2022-12-31 ┆ 12:52 ┆ Saturday ┆ DON MILLS STATION      ┆ … ┆ 0       ┆ W     ┆ SHP  ┆ 6166    │
└────────────┴───────┴──────────┴────────────────────────┴───┴─────────┴───────┴──────┴─────────┘

In [23]:
df_2022 = df_2022.with_columns(
    pl.col("Time").str.to_time("%H:%M")
)
df_2022.glimpse()

Rows: 19895
Columns: 10
$ Date      <date> 2022-01-01, 2022-01-01, 2022-01-01, 2022-01-01, 2022-01-01, 2022-01-01, 2022-01-01, 2022-01-01, 2022-01-01, 2022-01-01
$ Time      <time> 15:59:00, 02:23:00, 22:00:00, 02:28:00, 02:34:00, 05:40:00, 06:56:00, 06:58:00, 07:01:00, 07:43:00
$ Day        <str> 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday'
$ Station    <str> 'LAWRENCE EAST STATION', 'SPADINA BD STATION', 'KENNEDY SRT STATION TO', 'VAUGHAN MC STATION', 'EGLINTON STATION', 'QUEEN STATION', 'DAVISVILLE STATION', 'ST PATRICK STATION', 'PAPE STATION', 'WILSON STATION'
$ Code       <str> 'SRDP', 'MUIS', 'MRO', 'MUIS', 'MUATC', 'MUNCA', 'MUNCA', 'MUNCA', 'MUNCA', 'TUATC'
$ Min Delay  <i64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 10
$ Min Gap    <i64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ Bound      <str> 'N', null, null, null, 'S', null, null, null, null, 'S'
$ Line       <str> 'SRT', 'BD', 'SRT', 'YU', 'YU', 'YU', 'YU', 'YU', 'BD', 'YU'
$ Vehicle    <i64> 3023, 0, 0, 0, 5981, 0, 0, 0, 0, 5896

In [24]:
df_since_22 = pl.concat([df_2022, df_since_23])
df_since_22.glimpse()

Rows: 109967
Columns: 10
$ Date      <date> 2022-01-01, 2022-01-01, 2022-01-01, 2022-01-01, 2022-01-01, 2022-01-01, 2022-01-01, 2022-01-01, 2022-01-01, 2022-01-01
$ Time      <time> 15:59:00, 02:23:00, 22:00:00, 02:28:00, 02:34:00, 05:40:00, 06:56:00, 06:58:00, 07:01:00, 07:43:00
$ Day        <str> 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday', 'Saturday'
$ Station    <str> 'LAWRENCE EAST STATION', 'SPADINA BD STATION', 'KENNEDY SRT STATION TO', 'VAUGHAN MC STATION', 'EGLINTON STATION', 'QUEEN STATION', 'DAVISVILLE STATION', 'ST PATRICK STATION', 'PAPE STATION', 'WILSON STATION'
$ Code       <str> 'SRDP', 'MUIS', 'MRO', 'MUIS', 'MUATC', 'MUNCA', 'MUNCA', 'MUNCA', 'MUNCA', 'TUATC'
$ Min Delay  <i64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 10
$ Min Gap    <i64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ Bound      <str> 'N', null, null, null, 'S', null, null, null, null, 'S'
$ Line       <str> 'SRT', 'BD', 'SRT', 'YU', 'YU', 'YU', 'YU', 'YU', 'BD', 'YU'
$ Vehicle    <i64> 3023, 0, 0, 0, 5981, 0, 0, 0, 0, 5896

In [25]:
df_2021_path = data_dir / "ttc-subway-delay-data-2021.xlsx"
sheets_dict_21 = pl.read_excel(df_2021_path, sheet_id=0)
print("Sheet names:", sheets_dict_21.keys())

Sheet names: dict_keys(['January21', 'Feb 21', "March '21", "April '21", "May '21", 'June 21', 'July 21', 'August 21', 'Sept 21', 'Oct 21', 'Nov 21', 'December21'])

/var/folders/ch/33mzvf3519l1kk_ktmcysmc80000gn/T/ipykernel_81715/2677529192.py:2: FutureWarning: from_arrow(<ArrowStreamExportable>) will return a Series instead of a DataFrame in 2.0. To avoid this warning, pass the ArrowStreamExportable to either `pl.DataFrame` or `pl.Series` instead based on your desired output type.
  sheets_dict_21 = pl.read_excel(df_2021_path, sheet_id=0)

In [43]:
def check_months_columns(df_dict):
    cols_dict = {}
    for sheet_name, df in df_dict.items():
        # 1. Check for mismatched datatypes
        for col in df.columns:
            if col in cols_dict:
                if df[col].dtype != cols_dict[col]:
                    print(f"⚠️ TYPE MISMATCH: {sheet_name} '{col}' is {df[col].dtype}, but was previously {cols_dict[col]}")
                    return
            else:
                # Record the datatype the first time we see a column
                cols_dict[col] = df[col].dtype
                
        # 2. Check if the current sheet is missing any previously seen columns
        for known_col in cols_dict:
            if known_col not in df.columns:
                print(f"⚠️ MISSING COLUMN: {sheet_name} is missing '{known_col}'")
                return
    print("all columns match")

In [45]:
check_months_columns(sheets_dict_21)

all columns match

In [37]:
df_2021 = pl.concat(list(sheets_dict_21.values()))
df_2021

shape: (16_370, 10)
┌────────────┬───────┬────────┬───────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time  ┆ Day    ┆ Station               ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---   ┆ ---    ┆ ---                   ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ str   ┆ str    ┆ str                   ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪═══════╪════════╪═══════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2021-01-01 ┆ 00:33 ┆ Friday ┆ BLOOR STATION         ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 6046    │
│ 2021-01-01 ┆ 00:39 ┆ Friday ┆ SHERBOURNE STATION    ┆ … ┆ 9       ┆ E     ┆ BD   ┆ 5250    │
│ 2021-01-01 ┆ 01:07 ┆ Friday ┆ KENNEDY BD STATION    ┆ … ┆ 9       ┆ E     ┆ BD   ┆ 5249    │
│ 2021-01-01 ┆ 01:41 ┆ Friday ┆ ST CLAIR STATION      ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2021-01-01 ┆ 02:04 ┆ Friday ┆ SHEPPARD WEST STATION ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ …          ┆ …     ┆ …      ┆ …                     ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2021-12-31 ┆ 01:10 ┆ Friday ┆ MUSEUM STATION        ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5591    │
│ 2021-12-31 ┆ 01:12 ┆ Friday ┆ FINCH STATION         ┆ … ┆ 10      ┆ S     ┆ YU   ┆ 5983    │
│ 2021-12-31 ┆ 01:21 ┆ Friday ┆ EGLINTON WEST STATION ┆ … ┆ 8       ┆ N     ┆ YU   ┆ 6046    │
│ 2021-12-31 ┆ 01:37 ┆ Friday ┆ SHEPPARD WEST STATION ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 5536    │
│ 2021-12-31 ┆ 07:00 ┆ Friday ┆ DON MILLS STATION     ┆ … ┆ 0       ┆ E     ┆ SHP  ┆ 6146    │
└────────────┴───────┴────────┴───────────────────────┴───┴─────────┴───────┴──────┴─────────┘

In [38]:
df_2021 = df_2021.with_columns(
    pl.col("Time").str.to_time("%H:%M")
)
df_2021

shape: (16_370, 10)
┌────────────┬──────────┬────────┬───────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time     ┆ Day    ┆ Station               ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---      ┆ ---    ┆ ---                   ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ time     ┆ str    ┆ str                   ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪══════════╪════════╪═══════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2021-01-01 ┆ 00:33:00 ┆ Friday ┆ BLOOR STATION         ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 6046    │
│ 2021-01-01 ┆ 00:39:00 ┆ Friday ┆ SHERBOURNE STATION    ┆ … ┆ 9       ┆ E     ┆ BD   ┆ 5250    │
│ 2021-01-01 ┆ 01:07:00 ┆ Friday ┆ KENNEDY BD STATION    ┆ … ┆ 9       ┆ E     ┆ BD   ┆ 5249    │
│ 2021-01-01 ┆ 01:41:00 ┆ Friday ┆ ST CLAIR STATION      ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2021-01-01 ┆ 02:04:00 ┆ Friday ┆ SHEPPARD WEST STATION ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ …          ┆ …        ┆ …      ┆ …                     ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2021-12-31 ┆ 01:10:00 ┆ Friday ┆ MUSEUM STATION        ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5591    │
│ 2021-12-31 ┆ 01:12:00 ┆ Friday ┆ FINCH STATION         ┆ … ┆ 10      ┆ S     ┆ YU   ┆ 5983    │
│ 2021-12-31 ┆ 01:21:00 ┆ Friday ┆ EGLINTON WEST STATION ┆ … ┆ 8       ┆ N     ┆ YU   ┆ 6046    │
│ 2021-12-31 ┆ 01:37:00 ┆ Friday ┆ SHEPPARD WEST STATION ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 5536    │
│ 2021-12-31 ┆ 07:00:00 ┆ Friday ┆ DON MILLS STATION     ┆ … ┆ 0       ┆ E     ┆ SHP  ┆ 6146    │
└────────────┴──────────┴────────┴───────────────────────┴───┴─────────┴───────┴──────┴─────────┘

In [39]:
df_since_21 = pl.concat([df_2021, df_since_22])
df_since_21

shape: (126_337, 10)
┌────────────┬──────────┬─────────┬────────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time     ┆ Day     ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---      ┆ ---     ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ time     ┆ str     ┆ str                    ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪══════════╪═════════╪════════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2021-01-01 ┆ 00:33:00 ┆ Friday  ┆ BLOOR STATION          ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 6046    │
│ 2021-01-01 ┆ 00:39:00 ┆ Friday  ┆ SHERBOURNE STATION     ┆ … ┆ 9       ┆ E     ┆ BD   ┆ 5250    │
│ 2021-01-01 ┆ 01:07:00 ┆ Friday  ┆ KENNEDY BD STATION     ┆ … ┆ 9       ┆ E     ┆ BD   ┆ 5249    │
│ 2021-01-01 ┆ 01:41:00 ┆ Friday  ┆ ST CLAIR STATION       ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2021-01-01 ┆ 02:04:00 ┆ Friday  ┆ SHEPPARD WEST STATION  ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ …          ┆ …        ┆ …       ┆ …                      ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2026-06-30 ┆ 01:37:00 ┆ Tuesday ┆ KENNEDY BD STATION     ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 0       │
│ 2026-06-30 ┆ 17:57:00 ┆ Tuesday ┆ SHEPPARD-YONGE STATION ┆ … ┆ 0       ┆ W     ┆ SHP  ┆ 6191    │
│ 2026-06-30 ┆ 18:53:00 ┆ Tuesday ┆ DON MILLS STATION      ┆ … ┆ 0       ┆ null  ┆ SHP  ┆ 0       │
│ 2026-06-30 ┆ 21:04:00 ┆ Tuesday ┆ SHEPPARD-YONGE STATION ┆ … ┆ 0       ┆ E     ┆ SHP  ┆ 6161    │
│ 2026-06-30 ┆ 21:26:00 ┆ Tuesday ┆ SHEPPARD-YONGE STATION ┆ … ┆ 9       ┆ W     ┆ SHP  ┆ 6176    │
└────────────┴──────────┴─────────┴────────────────────────┴───┴─────────┴───────┴──────┴─────────┘

In [40]:
df_2020_path = data_dir / "ttc-subway-delay-data-2020.xlsx"
sheets_dict_20 = pl.read_excel(df_2020_path, sheet_id=0)
print("Sheet names:", sheets_dict_20.keys())

Sheet names: dict_keys(['Jan 2020', 'Feb 20', "March '20", "April '20", "May '20", 'June20', "July '20", "August '20", "Sept '20", "Oct '20", "Nov '20", 'Dec 2020'])

/var/folders/ch/33mzvf3519l1kk_ktmcysmc80000gn/T/ipykernel_81715/2718335173.py:2: FutureWarning: from_arrow(<ArrowStreamExportable>) will return a Series instead of a DataFrame in 2.0. To avoid this warning, pass the ArrowStreamExportable to either `pl.DataFrame` or `pl.Series` instead based on your desired output type.
  sheets_dict_20 = pl.read_excel(df_2020_path, sheet_id=0)

In [47]:
check_months_columns(sheets_dict_20)

all columns match

In [48]:
df_2020 = pl.concat(list(sheets_dict_20.values()))
df_2020

shape: (14_782, 10)
┌────────────┬───────┬───────────┬────────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time  ┆ Day       ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---   ┆ ---       ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ str   ┆ str       ┆ str                    ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪═══════╪═══════════╪════════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2020-01-01 ┆ 01:18 ┆ Wednesday ┆ KENNEDY SRT STATION    ┆ … ┆ 13      ┆ N     ┆ SRT  ┆ 3025    │
│ 2020-01-01 ┆ 01:27 ┆ Wednesday ┆ SHEPPARD WEST STATION  ┆ … ┆ 12      ┆ S     ┆ YU   ┆ 5591    │
│ 2020-01-01 ┆ 02:22 ┆ Wednesday ┆ MAIN STREET STATION    ┆ … ┆ 7       ┆ W     ┆ BD   ┆ 5371    │
│ 2020-01-01 ┆ 03:54 ┆ Wednesday ┆ KIPLING STATION        ┆ … ┆ 0       ┆ E     ┆ BD   ┆ 5243    │
│ 2020-01-01 ┆ 08:07 ┆ Wednesday ┆ KEELE STATION          ┆ … ┆ 9       ┆ W     ┆ BD   ┆ 5011    │
│ …          ┆ …     ┆ …         ┆ …                      ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2020-12-31 ┆ 22:21 ┆ Thursday  ┆ VICTORIA PARK STATION  ┆ … ┆ 9       ┆ W     ┆ BD   ┆ 5089    │
│ 2020-12-31 ┆ 22:35 ┆ Thursday  ┆ SPADINA BD STATION     ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ 2020-12-31 ┆ 23:23 ┆ Thursday  ┆ BAY STATION            ┆ … ┆ 15      ┆ E     ┆ BD   ┆ 5311    │
│ 2020-12-31 ┆ 23:34 ┆ Thursday  ┆ QUEEN STATION          ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 5976    │
│ 2020-12-31 ┆ 23:56 ┆ Thursday  ┆ SHEPPARD-YONGE STATION ┆ … ┆ 0       ┆ E     ┆ SHP  ┆ 6176    │
└────────────┴───────┴───────────┴────────────────────────┴───┴─────────┴───────┴──────┴─────────┘

In [50]:
df_2020 = df_2020.with_columns(
    pl.col("Time").str.to_time("%H:%M")
)

In [51]:
df_since_20 = pl.concat([df_2020, df_since_21])
df_since_20

shape: (141_119, 10)
┌────────────┬──────────┬───────────┬───────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time     ┆ Day       ┆ Station               ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---      ┆ ---       ┆ ---                   ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ time     ┆ str       ┆ str                   ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪══════════╪═══════════╪═══════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2020-01-01 ┆ 01:18:00 ┆ Wednesday ┆ KENNEDY SRT STATION   ┆ … ┆ 13      ┆ N     ┆ SRT  ┆ 3025    │
│ 2020-01-01 ┆ 01:27:00 ┆ Wednesday ┆ SHEPPARD WEST STATION ┆ … ┆ 12      ┆ S     ┆ YU   ┆ 5591    │
│ 2020-01-01 ┆ 02:22:00 ┆ Wednesday ┆ MAIN STREET STATION   ┆ … ┆ 7       ┆ W     ┆ BD   ┆ 5371    │
│ 2020-01-01 ┆ 03:54:00 ┆ Wednesday ┆ KIPLING STATION       ┆ … ┆ 0       ┆ E     ┆ BD   ┆ 5243    │
│ 2020-01-01 ┆ 08:07:00 ┆ Wednesday ┆ KEELE STATION         ┆ … ┆ 9       ┆ W     ┆ BD   ┆ 5011    │
│ …          ┆ …        ┆ …         ┆ …                     ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2026-06-30 ┆ 01:37:00 ┆ Tuesday   ┆ KENNEDY BD STATION    ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 0       │
│ 2026-06-30 ┆ 17:57:00 ┆ Tuesday   ┆ SHEPPARD-YONGE        ┆ … ┆ 0       ┆ W     ┆ SHP  ┆ 6191    │
│            ┆          ┆           ┆ STATION               ┆   ┆         ┆       ┆      ┆         │
│ 2026-06-30 ┆ 18:53:00 ┆ Tuesday   ┆ DON MILLS STATION     ┆ … ┆ 0       ┆ null  ┆ SHP  ┆ 0       │
│ 2026-06-30 ┆ 21:04:00 ┆ Tuesday   ┆ SHEPPARD-YONGE        ┆ … ┆ 0       ┆ E     ┆ SHP  ┆ 6161    │
│            ┆          ┆           ┆ STATION               ┆   ┆         ┆       ┆      ┆         │
│ 2026-06-30 ┆ 21:26:00 ┆ Tuesday   ┆ SHEPPARD-YONGE        ┆ … ┆ 9       ┆ W     ┆ SHP  ┆ 6176    │
│            ┆          ┆           ┆ STATION               ┆   ┆         ┆       ┆      ┆         │
└────────────┴──────────┴───────────┴───────────────────────┴───┴─────────┴───────┴──────┴─────────┘

In [52]:
df_2019_path = data_dir / "ttc-subway-delay-data-2019.xlsx"
df_2018_path = data_dir / "ttc-subway-delay-data-2018.xlsx"

In [56]:
sheets_dict_19 = pl.read_excel(df_2019_path, sheet_id=0)
sheets_dict_18 = pl.read_excel(df_2018_path, sheet_id=0)
print(sheets_dict_19.values())

dict_values([shape: (1_871, 10)
┌────────────┬───────┬──────────┬────────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time  ┆ Day      ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---   ┆ ---      ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ str   ┆ str      ┆ str                    ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪═══════╪══════════╪════════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2019-01-01 ┆ 01:08 ┆ Tuesday  ┆ YORK MILLS STATION     ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 5766    │
│ 2019-01-01 ┆ 02:14 ┆ Tuesday  ┆ ST ANDREW STATION      ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2019-01-01 ┆ 02:16 ┆ Tuesday  ┆ JANE STATION           ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 5117    │
│ 2019-01-01 ┆ 02:27 ┆ Tuesday  ┆ BLOOR STATION          ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5436    │
│ 2019-01-01 ┆ 03:03 ┆ Tuesday  ┆ DUPONT STATION         ┆ … ┆ 16      ┆ N     ┆ YU   ┆ 6061    │
│ …          ┆ …     ┆ …        ┆ …                      ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2019-01-31 ┆ 22:06 ┆ Thursday ┆ GREENWOOD STATION      ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 5071    │
│ 2019-01-31 ┆ 22:30 ┆ Thursday ┆ YUS/BD/SHEPPARD SUBWAY ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2019-01-31 ┆ 23:20 ┆ Thursday ┆ BLOOR DANFORTH SUBWAY  ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ 2019-01-31 ┆ 23:26 ┆ Thursday ┆ VICTORIA PARK STATION  ┆ … ┆ 0       ┆ E     ┆ BD   ┆ 5369    │
│ 2019-01-31 ┆ 23:31 ┆ Thursday ┆ YORKDALE STATION       ┆ … ┆ 10      ┆ N     ┆ YU   ┆ 5876    │
└────────────┴───────┴──────────┴────────────────────────┴───┴─────────┴───────┴──────┴─────────┘, shape: (1_598, 10)
┌────────────┬───────┬──────────┬───────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time  ┆ Day      ┆ Station               ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---   ┆ ---      ┆ ---                   ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ str   ┆ str      ┆ str                   ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪═══════╪══════════╪═══════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2019-02-01 ┆ 00:17 ┆ Friday   ┆ DUNDAS STATION        ┆ … ┆ 11      ┆ S     ┆ YU   ┆ 5686    │
│ 2019-02-01 ┆ 00:35 ┆ Friday   ┆ BLOOR DANFORTH SUBWAY ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ 2019-02-01 ┆ 00:48 ┆ Friday   ┆ ST ANDREW STATION     ┆ … ┆ 10      ┆ S     ┆ YU   ┆ 5431    │
│ 2019-02-01 ┆ 00:52 ┆ Friday   ┆ SHEPPARD WEST STATION ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 5741    │
│ 2019-02-01 ┆ 01:26 ┆ Friday   ┆ SHEPPARD WEST STATION ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 0       │
│ …          ┆ …     ┆ …        ┆ …                     ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2019-02-28 ┆ 23:10 ┆ Thursday ┆ ST GEORGE BD STATION  ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ 2019-02-28 ┆ 23:17 ┆ Thursday ┆ BATHURST STATION      ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 0       │
│ 2019-02-28 ┆ 23:18 ┆ Thursday ┆ ST GEORGE YUS STATION ┆ … ┆ 9       ┆ S     ┆ YU   ┆ 5856    │
│ 2019-02-28 ┆ 23:41 ┆ Thursday ┆ SHERBOURNE STATION    ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ 2019-02-28 ┆ 23:46 ┆ Thursday ┆ BLOOR DANFORTH SUBWAY ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
└────────────┴───────┴──────────┴───────────────────────┴───┴─────────┴───────┴──────┴─────────┘, shape: (1_503, 10)
┌────────────┬───────┬────────┬────────────────────────┬───┬─────────┬───────┬───────┬─────────┐
│ Date       ┆ Time  ┆ Day    ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line  ┆ Vehicle │
│ ---        ┆ ---   ┆ ---    ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---     │
│ date       ┆ str   ┆ str    ┆ str                    ┆   ┆ i64     ┆ str   ┆ str   ┆ i64     │
╞════════════╪═══════╪════════╪════════════════════════╪═══╪═════════╪═══════╪═══════╪═════════╡
│ 2019-03-01 ┆ 00:04 ┆ Friday ┆ WILSON STATION         ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ 2019-03-01 ┆ 00:19 ┆ Friday ┆ DUPONT STATION         ┆ … ┆ 0       ┆ S     ┆ YU    ┆ 5826    │
│ 2019-03-01 ┆ 00:22 ┆ Friday ┆ ISLINGTON STATION      ┆ … ┆ 9       ┆ W     ┆ BD    ┆ 5241    │
│ 2019-03-01 ┆ 00:43 ┆ Friday ┆ SHERBOURNE STATION     ┆ … ┆ 0       ┆ E     ┆ BD    ┆ 5291    │
│ 2019-03-01 ┆ 00:59 ┆ Friday ┆ KENNEDY BD STATION     ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
│ …          ┆ …     ┆ …      ┆ …                      ┆ … ┆ …       ┆ …     ┆ …     ┆ …       │
│ 2019-03-31 ┆ 20:19 ┆ Sunday ┆ YORKDALE STATION       ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ 2019-03-31 ┆ 21:21 ┆ Sunday ┆ COXWELL STATION        ┆ … ┆ 0       ┆ E     ┆ BD    ┆ 5245    │
│ 2019-03-31 ┆ 22:00 ┆ Sunday ┆ YUS/BD/SHEPPARD SUBWAY ┆ … ┆ 0       ┆ null  ┆ YU/BD ┆ 0       │
│ 2019-03-31 ┆ 22:13 ┆ Sunday ┆ BLOOR DANFORTH SUBWAY  ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
│ 2019-03-31 ┆ 22:53 ┆ Sunday ┆ WARDEN STATION         ┆ … ┆ 0       ┆ E     ┆ BD    ┆ 5328    │
└────────────┴───────┴────────┴────────────────────────┴───┴─────────┴───────┴───────┴─────────┘, shape: (1_550, 10)
┌────────────┬───────┬─────────┬────────────────────────┬───┬─────────┬───────┬───────┬─────────┐
│ Date       ┆ Time  ┆ Day     ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line  ┆ Vehicle │
│ ---        ┆ ---   ┆ ---     ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---     │
│ date       ┆ str   ┆ str     ┆ str                    ┆   ┆ i64     ┆ str   ┆ str   ┆ i64     │
╞════════════╪═══════╪═════════╪════════════════════════╪═══╪═════════╪═══════╪═══════╪═════════╡
│ 2019-04-01 ┆ 00:02 ┆ Monday  ┆ SHERBOURNE STATION     ┆ … ┆ 8       ┆ E     ┆ BD    ┆ 5245    │
│ 2019-04-01 ┆ 01:11 ┆ Monday  ┆ WILSON STATION         ┆ … ┆ 0       ┆ N     ┆ YU    ┆ 5541    │
│ 2019-04-01 ┆ 01:48 ┆ Monday  ┆ KIPLING STATION        ┆ … ┆ 0       ┆ W     ┆ BD    ┆ 0       │
│ 2019-04-01 ┆ 02:18 ┆ Monday  ┆ DAVISVILLE YARD        ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ 2019-04-01 ┆ 05:26 ┆ Monday  ┆ ST ANDREW STATION      ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ …          ┆ …     ┆ …       ┆ …                      ┆ … ┆ …       ┆ …     ┆ …     ┆ …       │
│ 2019-04-30 ┆ 22:00 ┆ Tuesday ┆ YUS/BD/SHEPPARD SUBWAY ┆ … ┆ 0       ┆ null  ┆ YU/BD ┆ 0       │
│ 2019-04-30 ┆ 22:07 ┆ Tuesday ┆ ROYAL YORK STATION     ┆ … ┆ 0       ┆ E     ┆ BD    ┆ 5097    │
│ 2019-04-30 ┆ 22:12 ┆ Tuesday ┆ ROYAL YORK STATION     ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
│ 2019-04-30 ┆ 22:24 ┆ Tuesday ┆ KIPLING STATION        ┆ … ┆ 0       ┆ W     ┆ BD    ┆ 5098    │
│ 2019-04-30 ┆ 23:52 ┆ Tuesday ┆ BATHURST STATION       ┆ … ┆ 0       ┆ E     ┆ BD    ┆ 0       │
└────────────┴───────┴─────────┴────────────────────────┴───┴─────────┴───────┴───────┴─────────┘, shape: (1_705, 10)
┌────────────┬───────┬───────────┬────────────────────────┬───┬─────────┬───────┬───────┬─────────┐
│ Date       ┆ Time  ┆ Day       ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line  ┆ Vehicle │
│ ---        ┆ ---   ┆ ---       ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---     │
│ date       ┆ str   ┆ str       ┆ str                    ┆   ┆ i64     ┆ str   ┆ str   ┆ i64     │
╞════════════╪═══════╪═══════════╪════════════════════════╪═══╪═════════╪═══════╪═══════╪═════════╡
│ 2019-05-01 ┆ 01:25 ┆ Wednesday ┆ YONGE BD STATION       ┆ … ┆ 15      ┆ W     ┆ BD    ┆ 5042    │
│ 2019-05-01 ┆ 01:58 ┆ Wednesday ┆ CHESTER STATION        ┆ … ┆ 0       ┆ W     ┆ BD    ┆ 5205    │
│ 2019-05-01 ┆ 02:51 ┆ Wednesday ┆ WILSON STATION         ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ 2019-05-01 ┆ 05:50 ┆ Wednesday ┆ FINCH STATION          ┆ … ┆ 8       ┆ S     ┆ YU    ┆ 5771    │
│ 2019-05-01 ┆ 06:07 ┆ Wednesday ┆ WILSON STATION         ┆ … ┆ 5       ┆ S     ┆ YU    ┆ 5821    │
│ …          ┆ …     ┆ …         ┆ …                      ┆ … ┆ …       ┆ …     ┆ …     ┆ …       │
│ 2019-05-31 ┆ 21:18 ┆ Friday    ┆ GLENCAIRN STATION      ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ 2019-05-31 ┆ 22:00 ┆ Friday    ┆ YUS/BD/SHEPPARD SUBWAY ┆ … ┆ 0       ┆ null  ┆ YU/BD ┆ 0       │
│ 2019-05-31 ┆ 22:04 ┆ Friday    ┆ COXWELL STATION        ┆ … ┆ 7       ┆ E     ┆ BD    ┆ 5155    │
│ 2019-05-31 ┆ 22:57 ┆ Friday    ┆ OSGOODE STATION        ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ 2019-05-31 ┆ 23:56 ┆ Friday    ┆ KEELE STATION          ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
└────────────┴───────┴───────────┴────────────────────────┴───┴─────────┴───────┴───────┴─────────┘, shape: (1_604, 10)
┌────────────┬───────┬──────────┬───────────────────────┬───┬─────────┬───────┬───────┬─────────┐
│ Date       ┆ Time  ┆ Day      ┆ Station               ┆ … ┆ Min Gap ┆ Bound ┆ Line  ┆ Vehicle │
│ ---        ┆ ---   ┆ ---      ┆ ---                   ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---     │
│ date       ┆ str   ┆ str      ┆ str                   ┆   ┆ i64     ┆ str   ┆ str   ┆ i64     │
╞════════════╪═══════╪══════════╪═══════════════════════╪═══╪═════════╪═══════╪═══════╪═════════╡
│ 2019-06-01 ┆ 01:46 ┆ Saturday ┆ ST PATRICK STATION    ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ 2019-06-01 ┆ 02:35 ┆ Saturday ┆ ISLINGTON STATION     ┆ … ┆ 0       ┆ E     ┆ BD    ┆ 5118    │
│ 2019-06-01 ┆ 05:11 ┆ Saturday ┆ JANE STATION          ┆ … ┆ 0       ┆ E     ┆ BD    ┆ 5260    │
│ 2019-06-01 ┆ 05:26 ┆ Saturday ┆ WILSON HOSTLER        ┆ … ┆ 0       ┆ S     ┆ YU    ┆ 5636    │
│ 2019-06-01 ┆ 05:29 ┆ Saturday ┆ WILSON HOSTLER        ┆ … ┆ 0       ┆ N     ┆ YU    ┆ 5636    │
│ …          ┆ …     ┆ …        ┆ …                     ┆ … ┆ …       ┆ …     ┆ …     ┆ …       │
│ 2019-06-30 ┆ 21:09 ┆ Sunday   ┆ LANSDOWNE STATION     ┆ … ┆ 15      ┆ W     ┆ BD    ┆ 5226    │
│ 2019-06-30 ┆ 21:46 ┆ Sunday   ┆ COXWELL STATION       ┆ … ┆ 8       ┆ E     ┆ BD    ┆ 5237    │
│ 2019-06-30 ┆ 21:55 ┆ Sunday   ┆ GREENWOOD STATION     ┆ … ┆ 0       ┆ E     ┆ BD    ┆ 5086    │
│ 2019-06-30 ┆ 22:00 ┆ Sunday   ┆ YUS/BD/SEPPARD SUBWAY ┆ … ┆ 0       ┆ null  ┆ YU/BD ┆ 0       │
│ 2019-06-30 ┆ 22:45 ┆ Sunday   ┆ BLOOR DANFORTH SUBWAY ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
└────────────┴───────┴──────────┴───────────────────────┴───┴─────────┴───────┴───────┴─────────┘, shape: (1_696, 10)
┌────────────┬───────┬───────────┬──────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time  ┆ Day       ┆ Station              ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---   ┆ ---       ┆ ---                  ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ str   ┆ str       ┆ str                  ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪═══════╪═══════════╪══════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2019-07-01 ┆ 00:10 ┆ Monday    ┆ YORK MILLS STATION   ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 5991    │
│ 2019-07-01 ┆ 00:44 ┆ Monday    ┆ WARDEN STATION       ┆ … ┆ 18      ┆ W     ┆ BD   ┆ 5186    │
│ 2019-07-01 ┆ 05:53 ┆ Monday    ┆ COXWELL STATION      ┆ … ┆ 0       ┆ E     ┆ BD   ┆ 5015    │
│ 2019-07-01 ┆ 05:57 ┆ Monday    ┆ ST PATRICK STATION   ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 5746    │
│ 2019-07-01 ┆ 06:15 ┆ Monday    ┆ MCCOWAN STATION      ┆ … ┆ 9       ┆ N     ┆ SRT  ┆ 3021    │
│ …          ┆ …     ┆ …         ┆ …                    ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2019-07-31 ┆ 22:23 ┆ Wednesday ┆ KENNEDY BD STATION   ┆ … ┆ 0       ┆ E     ┆ BD   ┆ 5070    │
│ 2019-07-31 ┆ 22:42 ┆ Wednesday ┆ ST GEORGE BD STATION ┆ … ┆ 8       ┆ W     ┆ BD   ┆ 5110    │
│ 2019-07-31 ┆ 23:00 ┆ Wednesday ┆ UNION STATION        ┆ … ┆ 10      ┆ N     ┆ YU   ┆ 5951    │
│ 2019-07-31 ┆ 23:17 ┆ Wednesday ┆ COLLEGE STATION      ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 5476    │
│ 2019-07-31 ┆ 23:51 ┆ Wednesday ┆ ROSEDALE STATION     ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5806    │
└────────────┴───────┴───────────┴──────────────────────┴───┴─────────┴───────┴──────┴─────────┘, shape: (1_630, 10)
┌────────────┬───────┬──────────┬────────────────────────┬───┬─────────┬───────┬───────┬─────────┐
│ Date       ┆ Time  ┆ Day      ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line  ┆ Vehicle │
│ ---        ┆ ---   ┆ ---      ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---     │
│ date       ┆ str   ┆ str      ┆ str                    ┆   ┆ i64     ┆ str   ┆ str   ┆ i64     │
╞════════════╪═══════╪══════════╪════════════════════════╪═══╪═════════╪═══════╪═══════╪═════════╡
│ 2019-08-01 ┆ 00:05 ┆ Thursday ┆ YONGE UNIVERSITY LINE  ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ 2019-08-01 ┆ 00:06 ┆ Thursday ┆ NORTH YORK CTR STATION ┆ … ┆ 0       ┆ S     ┆ YU    ┆ 5841    │
│ 2019-08-01 ┆ 01:30 ┆ Thursday ┆ DUFFERIN STATION       ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
│ 2019-08-01 ┆ 01:34 ┆ Thursday ┆ VAUGHAN MC STATION     ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ 2019-08-01 ┆ 01:42 ┆ Thursday ┆ BLOOR STATION          ┆ … ┆ 0       ┆ S     ┆ YU    ┆ 0       │
│ …          ┆ …     ┆ …        ┆ …                      ┆ … ┆ …       ┆ …     ┆ …     ┆ …       │
│ 2019-08-31 ┆ 21:53 ┆ Saturday ┆ EGLINTON STATION       ┆ … ┆ 8       ┆ S     ┆ YU    ┆ 5591    │
│ 2019-08-31 ┆ 22:00 ┆ Saturday ┆ YUS/BD/SHEPPARD SUBWAY ┆ … ┆ 0       ┆ null  ┆ YU/BD ┆ 0       │
│ 2019-08-31 ┆ 23:00 ┆ Saturday ┆ DAVISVILLE STATION     ┆ … ┆ 0       ┆ S     ┆ YU    ┆ 5916    │
│ 2019-08-31 ┆ 23:06 ┆ Saturday ┆ KIPLING STATION        ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
│ 2019-08-31 ┆ 23:17 ┆ Saturday ┆ SHERBOURNE STATION     ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
└────────────┴───────┴──────────┴────────────────────────┴───┴─────────┴───────┴───────┴─────────┘, shape: (1_531, 10)
┌────────────┬───────┬────────┬────────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time  ┆ Day    ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---   ┆ ---    ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ str   ┆ str    ┆ str                    ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪═══════╪════════╪════════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2019-09-01 ┆ 00:30 ┆ Sunday ┆ FINCH STATION          ┆ … ┆ 0       ┆ null  ┆ null ┆ 0       │
│ 2019-09-01 ┆ 08:12 ┆ Sunday ┆ DAVISVILLE STATION     ┆ … ┆ 8       ┆ N     ┆ YU   ┆ 5896    │
│ 2019-09-01 ┆ 08:23 ┆ Sunday ┆ DAVISVILLE STATION     ┆ … ┆ 9       ┆ N     ┆ YU   ┆ 5846    │
│ 2019-09-01 ┆ 08:57 ┆ Sunday ┆ ST GEORGE BD STATION   ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ 2019-09-01 ┆ 10:09 ┆ Sunday ┆ SHEPPARD-YONGE STATION ┆ … ┆ 0       ┆ E     ┆ SHP  ┆ 6166    │
│ …          ┆ …     ┆ …      ┆ …                      ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2019-09-30 ┆ 22:04 ┆ Monday ┆ GREENWOOD STATION      ┆ … ┆ 0       ┆ E     ┆ BD   ┆ 5332    │
│ 2019-09-30 ┆ 22:30 ┆ Monday ┆ KEELE TO DUNDAS WEST   ┆ … ┆ 20      ┆ W     ┆ BD   ┆ 5105    │
│ 2019-09-30 ┆ 22:34 ┆ Monday ┆ ROYAL YORK STATION     ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ 2019-09-30 ┆ 23:00 ┆ Monday ┆ BLOOR DANFORTH SUBWAY  ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ 2019-09-30 ┆ 23:25 ┆ Monday ┆ WILSON STATION         ┆ … ┆ 8       ┆ S     ┆ YU   ┆ 5696    │
└────────────┴───────┴────────┴────────────────────────┴───┴─────────┴───────┴──────┴─────────┘, shape: (1_497, 10)
┌────────────┬───────┬──────────┬────────────────────────┬───┬─────────┬───────┬───────┬─────────┐
│ Date       ┆ Time  ┆ Day      ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line  ┆ Vehicle │
│ ---        ┆ ---   ┆ ---      ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---     │
│ date       ┆ str   ┆ str      ┆ str                    ┆   ┆ i64     ┆ str   ┆ str   ┆ i64     │
╞════════════╪═══════╪══════════╪════════════════════════╪═══╪═════════╪═══════╪═══════╪═════════╡
│ 2019-10-01 ┆ 00:08 ┆ Tuesday  ┆ ST GEORGE BD STATION   ┆ … ┆ 10      ┆ W     ┆ BD    ┆ 5227    │
│ 2019-10-01 ┆ 02:25 ┆ Tuesday  ┆ FINCH STATION          ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ 2019-10-01 ┆ 04:54 ┆ Tuesday  ┆ DAVISVILLE CARHOUSE    ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ 2019-10-01 ┆ 04:55 ┆ Tuesday  ┆ DON MILLS STATION      ┆ … ┆ 0       ┆ null  ┆ SHP   ┆ 0       │
│ 2019-10-01 ┆ 05:34 ┆ Tuesday  ┆ WELLESLEY STATION      ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ …          ┆ …     ┆ …        ┆ …                      ┆ … ┆ …       ┆ …     ┆ …     ┆ …       │
│ 2019-10-31 ┆ 21:42 ┆ Thursday ┆ FINCH WEST STATION     ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ 2019-10-31 ┆ 22:00 ┆ Thursday ┆ YUS/BD/SHEPPARD SUBWAY ┆ … ┆ 0       ┆ null  ┆ YU/BD ┆ 0       │
│ 2019-10-31 ┆ 22:27 ┆ Thursday ┆ FINCH STATION          ┆ … ┆ 0       ┆ S     ┆ YU    ┆ 5986    │
│ 2019-10-31 ┆ 22:39 ┆ Thursday ┆ QUEEN'S PARK STATION   ┆ … ┆ 8       ┆ N     ┆ YU    ┆ 5816    │
│ 2019-10-31 ┆ 23:15 ┆ Thursday ┆ ST GEORGE YUS STATION  ┆ … ┆ 0       ┆ S     ┆ YU    ┆ 5526    │
└────────────┴───────┴──────────┴────────────────────────┴───┴─────────┴───────┴───────┴─────────┘, shape: (1_463, 10)
┌────────────┬───────┬──────────┬────────────────────────┬───┬─────────┬───────┬───────┬─────────┐
│ Date       ┆ Time  ┆ Day      ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line  ┆ Vehicle │
│ ---        ┆ ---   ┆ ---      ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---     │
│ date       ┆ str   ┆ str      ┆ str                    ┆   ┆ i64     ┆ str   ┆ str   ┆ i64     │
╞════════════╪═══════╪══════════╪════════════════════════╪═══╪═════════╪═══════╪═══════╪═════════╡
│ 2019-11-01 ┆ 00:00 ┆ Friday   ┆ GLENCAIRN STATION      ┆ … ┆ 20      ┆ S     ┆ YU    ┆ 5526    │
│ 2019-11-01 ┆ 00:02 ┆ Friday   ┆ CHESTER STATION        ┆ … ┆ 0       ┆ W     ┆ BD    ┆ 0       │
│ 2019-11-01 ┆ 00:34 ┆ Friday   ┆ KEELE STATION          ┆ … ┆ 0       ┆ W     ┆ BD    ┆ 5182    │
│ 2019-11-01 ┆ 00:57 ┆ Friday   ┆ VICTORIA PARK STATION  ┆ … ┆ 9       ┆ W     ┆ BD    ┆ 5121    │
│ 2019-11-01 ┆ 02:41 ┆ Friday   ┆ FINCH STATION          ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ …          ┆ …     ┆ …        ┆ …                      ┆ … ┆ …       ┆ …     ┆ …     ┆ …       │
│ 2019-11-30 ┆ 20:21 ┆ Saturday ┆ ST GEORGE BD STATION   ┆ … ┆ 13      ┆ E     ┆ BD    ┆ 5280    │
│ 2019-11-30 ┆ 20:39 ┆ Saturday ┆ ST GEORGE BD STATION   ┆ … ┆ 0       ┆ E     ┆ BD    ┆ 5130    │
│ 2019-11-30 ┆ 21:58 ┆ Saturday ┆ DUNDAS WEST STATION    ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
│ 2019-11-30 ┆ 22:00 ┆ Saturday ┆ YUS/BD/SHEPPARD SUBWAY ┆ … ┆ 0       ┆ null  ┆ YU/BD ┆ 0       │
│ 2019-11-30 ┆ 23:28 ┆ Saturday ┆ WELLESLEY STATION      ┆ … ┆ 0       ┆ N     ┆ YU    ┆ 5521    │
└────────────┴───────┴──────────┴────────────────────────┴───┴─────────┴───────┴───────┴─────────┘, shape: (1_574, 10)
┌────────────┬───────┬─────────┬───────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time  ┆ Day     ┆ Station               ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---   ┆ ---     ┆ ---                   ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ str   ┆ str     ┆ str                   ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪═══════╪═════════╪═══════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2019-12-01 ┆ 00:23 ┆ Sunday  ┆ WARDEN STATION        ┆ … ┆ 10      ┆ E     ┆ BD   ┆ 5117    │
│ 2019-12-01 ┆ 00:59 ┆ Sunday  ┆ OLD MILL STATION      ┆ … ┆ 10      ┆ E     ┆ BD   ┆ 5293    │
│ 2019-12-01 ┆ 01:13 ┆ Sunday  ┆ BROADVIEW STATION     ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 5221    │
│ 2019-12-01 ┆ 08:00 ┆ Sunday  ┆ BLOOR DANFORTH SUBWAY ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ 2019-12-01 ┆ 08:00 ┆ Sunday  ┆ BLOOR DANFORTH SUBWAY ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ …          ┆ …     ┆ …       ┆ …                     ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2019-12-31 ┆ 22:54 ┆ Tuesday ┆ FINCH STATION         ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2019-12-31 ┆ 23:09 ┆ Tuesday ┆ SHERBOURNE STATION    ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 5234    │
│ 2019-12-31 ┆ 23:12 ┆ Tuesday ┆ ST CLAIR WEST STATION ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │

/var/folders/ch/33mzvf3519l1kk_ktmcysmc80000gn/T/ipykernel_81715/2114164594.py:1: FutureWarning: from_arrow(<ArrowStreamExportable>) will return a Series instead of a DataFrame in 2.0. To avoid this warning, pass the ArrowStreamExportable to either `pl.DataFrame` or `pl.Series` instead based on your desired output type.
  sheets_dict_19 = pl.read_excel(df_2019_path, sheet_id=0)
/var/folders/ch/33mzvf3519l1kk_ktmcysmc80000gn/T/ipykernel_81715/2114164594.py:2: FutureWarning: from_arrow(<ArrowStreamExportable>) will return a Series instead of a DataFrame in 2.0. To avoid this warning, pass the ArrowStreamExportable to either `pl.DataFrame` or `pl.Series` instead based on your desired output type.
  sheets_dict_18 = pl.read_excel(df_2018_path, sheet_id=0)

In [57]:
print(sheets_dict_18.values())

dict_values([shape: (1_873, 10)
┌────────────┬───────┬───────────┬───────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time  ┆ Day       ┆ Station               ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---   ┆ ---       ┆ ---                   ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ str   ┆ str       ┆ str                   ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪═══════╪═══════════╪═══════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2018-01-01 ┆ 00:29 ┆ Monday    ┆ SHEPPARD WEST STATION ┆ … ┆ 15      ┆ N     ┆ YU   ┆ 5986    │
│ 2018-01-01 ┆ 01:07 ┆ Monday    ┆ DUNDAS STATION        ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2018-01-01 ┆ 01:22 ┆ Monday    ┆ MUSEUM STATION        ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5751    │
│ 2018-01-01 ┆ 01:28 ┆ Monday    ┆ BAY LOWER             ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 5222    │
│ 2018-01-01 ┆ 01:39 ┆ Monday    ┆ MUSEUM STATION        ┆ … ┆ 11      ┆ S     ┆ YU   ┆ 5781    │
│ …          ┆ …     ┆ …         ┆ …                     ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2018-01-31 ┆ 22:12 ┆ Wednesday ┆ CHRISTIE STATION      ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ 2018-01-31 ┆ 22:19 ┆ Wednesday ┆ COLLEGE STATION       ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5751    │
│ 2018-01-31 ┆ 22:39 ┆ Wednesday ┆ UNION STATION         ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5696    │
│ 2018-01-31 ┆ 23:04 ┆ Wednesday ┆ COLLEGE STATION       ┆ … ┆ 6       ┆ S     ┆ YU   ┆ 5416    │
│ 2018-01-31 ┆ 23:35 ┆ Wednesday ┆ YONGE UNIVERSITY LINE ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
└────────────┴───────┴───────────┴───────────────────────┴───┴─────────┴───────┴──────┴─────────┘, shape: (1_470, 10)
┌────────────┬───────┬───────────┬────────────────────────┬───┬─────────┬───────┬───────┬─────────┐
│ Date       ┆ Time  ┆ Day       ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line  ┆ Vehicle │
│ ---        ┆ ---   ┆ ---       ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---     │
│ date       ┆ str   ┆ str       ┆ str                    ┆   ┆ i64     ┆ str   ┆ str   ┆ i64     │
╞════════════╪═══════╪═══════════╪════════════════════════╪═══╪═════════╪═══════╪═══════╪═════════╡
│ 2018-02-01 ┆ 00:36 ┆ Thursday  ┆ RUNNYMEDE STATION      ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
│ 2018-02-01 ┆ 00:55 ┆ Thursday  ┆ MCCOWAN STATION        ┆ … ┆ 12      ┆ S     ┆ SRT   ┆ 3004    │
│ 2018-02-01 ┆ 01:03 ┆ Thursday  ┆ SUMMERHILL STATION     ┆ … ┆ 8       ┆ N     ┆ YU    ┆ 5516    │
│ 2018-02-01 ┆ 01:55 ┆ Thursday  ┆ LAWRENCE STATION       ┆ … ┆ 0       ┆ N     ┆ YU    ┆ 5466    │
│ 2018-02-01 ┆ 02:42 ┆ Thursday  ┆ WILSON STATION         ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ …          ┆ …     ┆ …         ┆ …                      ┆ … ┆ …       ┆ …     ┆ …     ┆ …       │
│ 2018-02-28 ┆ 21:26 ┆ Wednesday ┆ ST CLAIR STATION       ┆ … ┆ 12      ┆ N     ┆ YU    ┆ 5766    │
│ 2018-02-28 ┆ 22:00 ┆ Wednesday ┆ YUS/BD/SHEPPARD SUBWAY ┆ … ┆ 0       ┆ null  ┆ YU/BD ┆ 0       │
│ 2018-02-28 ┆ 22:37 ┆ Wednesday ┆ FINCH STATION          ┆ … ┆ 9       ┆ S     ┆ YU    ┆ 6021    │
│ 2018-02-28 ┆ 22:48 ┆ Wednesday ┆ ST GEORGE BD STATION   ┆ … ┆ 0       ┆ W     ┆ BD    ┆ 0       │
│ 2018-02-28 ┆ 23:30 ┆ Wednesday ┆ YONGE UNIVERSITY LINE  ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
└────────────┴───────┴───────────┴────────────────────────┴───┴─────────┴───────┴───────┴─────────┘, shape: (1_621, 10)
┌────────────┬───────┬──────────┬───────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time  ┆ Day      ┆ Station               ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---   ┆ ---      ┆ ---                   ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ str   ┆ str      ┆ str                   ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪═══════╪══════════╪═══════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2018-03-01 ┆ 00:05 ┆ Thursday ┆ BAYVIEW STATION       ┆ … ┆ 0       ┆ E     ┆ SHP  ┆ 6176    │
│ 2018-03-01 ┆ 00:11 ┆ Thursday ┆ YONGE SHP STATION     ┆ … ┆ 11      ┆ W     ┆ SHP  ┆ 0       │
│ 2018-03-01 ┆ 00:15 ┆ Thursday ┆ VAUGHAN MC STATION    ┆ … ┆ 9       ┆ S     ┆ YU   ┆ 5406    │
│ 2018-03-01 ┆ 00:18 ┆ Thursday ┆ VICTORIA PARK STATION ┆ … ┆ 9       ┆ W     ┆ BD   ┆ 5342    │
│ 2018-03-01 ┆ 00:32 ┆ Thursday ┆ ST CLAIR STATION      ┆ … ┆ 9       ┆ N     ┆ YU   ┆ 5941    │
│ …          ┆ …     ┆ …        ┆ …                     ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2018-03-31 ┆ 20:20 ┆ Saturday ┆ FINCH STATION         ┆ … ┆ 9       ┆ S     ┆ YU   ┆ 5506    │
│ 2018-03-31 ┆ 20:44 ┆ Saturday ┆ SUMMERHILL STATION    ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2018-03-31 ┆ 20:53 ┆ Saturday ┆ LAWRENCE WEST STATION ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2018-03-31 ┆ 21:09 ┆ Saturday ┆ OSSINGTON STATION     ┆ … ┆ 9       ┆ W     ┆ BD   ┆ 5093    │
│ 2018-03-31 ┆ 23:48 ┆ Saturday ┆ DONLANDS STATION      ┆ … ┆ 0       ┆ E     ┆ BD   ┆ 0       │
└────────────┴───────┴──────────┴───────────────────────┴───┴─────────┴───────┴──────┴─────────┘, shape: (1_597, 10)
┌────────────┬───────┬────────┬───────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time  ┆ Day    ┆ Station               ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---   ┆ ---    ┆ ---                   ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ str   ┆ str    ┆ str                   ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪═══════╪════════╪═══════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2018-04-01 ┆ 00:27 ┆ Sunday ┆ ST GEORGE BD STATION  ┆ … ┆ 12      ┆ W     ┆ BD   ┆ 5256    │
│ 2018-04-01 ┆ 07:56 ┆ Sunday ┆ FINCH STATION         ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 5751    │
│ 2018-04-01 ┆ 08:00 ┆ Sunday ┆ YONGE UNIVERSITY LINE ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2018-04-01 ┆ 09:50 ┆ Sunday ┆ KIPLING STATION       ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 5139    │
│ 2018-04-01 ┆ 10:18 ┆ Sunday ┆ VICTORIA PARK STATION ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 5354    │
│ …          ┆ …     ┆ …      ┆ …                     ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2018-04-30 ┆ 22:17 ┆ Monday ┆ SHEPPARD STATION      ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5901    │
│ 2018-04-30 ┆ 22:32 ┆ Monday ┆ SHEPPARD STATION      ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5511    │
│ 2018-04-30 ┆ 22:54 ┆ Monday ┆ SHEPPARD STATION      ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5556    │
│ 2018-04-30 ┆ 22:57 ┆ Monday ┆ SHEPPARD STATION      ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5511    │
│ 2018-04-30 ┆ 23:30 ┆ Monday ┆ BLOOR DANFORTH SUBWAY ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
└────────────┴───────┴────────┴───────────────────────┴───┴─────────┴───────┴──────┴─────────┘, shape: (1_761, 10)
┌────────────┬───────┬──────────┬────────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time  ┆ Day      ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---   ┆ ---      ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ str   ┆ str      ┆ str                    ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪═══════╪══════════╪════════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2018-05-01 ┆ 00:18 ┆ Tuesday  ┆ OLD MILL STATION       ┆ … ┆ 13      ┆ W     ┆ BD   ┆ 5077    │
│ 2018-05-01 ┆ 00:29 ┆ Tuesday  ┆ YUS/BD/SHEPPARD SUBWAY ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 5234    │
│ 2018-05-01 ┆ 02:01 ┆ Tuesday  ┆ MCCOWAN YARD           ┆ … ┆ 0       ┆ N     ┆ SRT  ┆ 3015    │
│ 2018-05-01 ┆ 02:41 ┆ Tuesday  ┆ VAUGHAN MC STATION     ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2018-05-01 ┆ 05:47 ┆ Tuesday  ┆ KIPLING STATION        ┆ … ┆ 0       ┆ E     ┆ BD   ┆ 5120    │
│ …          ┆ …     ┆ …        ┆ …                      ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2018-05-31 ┆ 22:08 ┆ Thursday ┆ WARDEN STATION         ┆ … ┆ 7       ┆ W     ┆ BD   ┆ 5271    │
│ 2018-05-31 ┆ 22:29 ┆ Thursday ┆ DON MILLS STATION      ┆ … ┆ 46      ┆ W     ┆ SHP  ┆ 6156    │
│ 2018-05-31 ┆ 22:49 ┆ Thursday ┆ VICTORIA PARK STATION  ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ 2018-05-31 ┆ 23:16 ┆ Thursday ┆ YUS/BD/SHEPPARD SUBWAY ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2018-05-31 ┆ 23:17 ┆ Thursday ┆ BLOOR DANFORTH SUBWAY  ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
└────────────┴───────┴──────────┴────────────────────────┴───┴─────────┴───────┴──────┴─────────┘, shape: (1_794, 10)
┌────────────┬───────┬──────────┬────────────────────────┬───┬─────────┬───────┬───────┬─────────┐
│ Date       ┆ Time  ┆ Day      ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line  ┆ Vehicle │
│ ---        ┆ ---   ┆ ---      ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---     │
│ date       ┆ str   ┆ str      ┆ str                    ┆   ┆ i64     ┆ str   ┆ str   ┆ i64     │
╞════════════╪═══════╪══════════╪════════════════════════╪═══╪═════════╪═══════╪═══════╪═════════╡
│ 2018-06-01 ┆ 00:17 ┆ Friday   ┆ SHEPPARD WEST STATION  ┆ … ┆ 5       ┆ N     ┆ YU    ┆ 5561    │
│ 2018-06-01 ┆ 01:29 ┆ Friday   ┆ DUFFERIN STATION       ┆ … ┆ 8       ┆ E     ┆ BD    ┆ 5033    │
│ 2018-06-01 ┆ 05:09 ┆ Friday   ┆ YONGE UNIVERSITY LINE  ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ 2018-06-01 ┆ 05:59 ┆ Friday   ┆ KIPLING STATION        ┆ … ┆ 0       ┆ E     ┆ BD    ┆ 5029    │
│ 2018-06-01 ┆ 06:21 ┆ Friday   ┆ KENNEDY BD STATION     ┆ … ┆ 8       ┆ W     ┆ BD    ┆ 5024    │
│ …          ┆ …     ┆ …        ┆ …                      ┆ … ┆ …       ┆ …     ┆ …     ┆ …       │
│ 2018-06-30 ┆ 22:00 ┆ Saturday ┆ YUS/BD/SHEPPARD SUBWAY ┆ … ┆ 0       ┆ null  ┆ YU/BD ┆ 0       │
│ 2018-06-30 ┆ 22:23 ┆ Saturday ┆ DAVISVILLE STATION     ┆ … ┆ 11      ┆ N     ┆ YU    ┆ 5606    │
│ 2018-06-30 ┆ 22:47 ┆ Saturday ┆ BLOOR DANFORTH SUBWAY  ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
│ 2018-06-30 ┆ 23:06 ┆ Saturday ┆ BATHURST STATION       ┆ … ┆ 0       ┆ W     ┆ BD    ┆ 5290    │
│ 2018-06-30 ┆ 23:26 ┆ Saturday ┆ ROYAL YORK STATION     ┆ … ┆ 7       ┆ W     ┆ BD    ┆ 5290    │
└────────────┴───────┴──────────┴────────────────────────┴───┴─────────┴───────┴───────┴─────────┘, shape: (1_885, 10)
┌────────────┬───────┬─────────┬────────────────────────┬───┬─────────┬───────┬───────┬─────────┐
│ Date       ┆ Time  ┆ Day     ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line  ┆ Vehicle │
│ ---        ┆ ---   ┆ ---     ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---     │
│ date       ┆ str   ┆ str     ┆ str                    ┆   ┆ i64     ┆ str   ┆ str   ┆ i64     │
╞════════════╪═══════╪═════════╪════════════════════════╪═══╪═════════╪═══════╪═══════╪═════════╡
│ 2018-07-01 ┆ 00:58 ┆ Sunday  ┆ ST GEORGE BD STATION   ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
│ 2018-07-01 ┆ 02:15 ┆ Sunday  ┆ ISLINGTON STATION      ┆ … ┆ 0       ┆ W     ┆ BD    ┆ 0       │
│ 2018-07-01 ┆ 06:20 ┆ Sunday  ┆ LANSDOWNE STATION      ┆ … ┆ 0       ┆ W     ┆ BD    ┆ 5254    │
│ 2018-07-01 ┆ 06:53 ┆ Sunday  ┆ CHRISTIE STATION       ┆ … ┆ 0       ┆ E     ┆ BD    ┆ 5172    │
│ 2018-07-01 ┆ 08:00 ┆ Sunday  ┆ SCARBOROUGH RAPID TRAN ┆ … ┆ 0       ┆ null  ┆ SRT   ┆ 0       │
│ …          ┆ …     ┆ …       ┆ …                      ┆ … ┆ …       ┆ …     ┆ …     ┆ …       │
│ 2018-07-31 ┆ 21:11 ┆ Tuesday ┆ DUNDAS STATION         ┆ … ┆ 0       ┆ S     ┆ YU    ┆ 0       │
│ 2018-07-31 ┆ 21:40 ┆ Tuesday ┆ DONLANDS STATION       ┆ … ┆ 11      ┆ W     ┆ BD    ┆ 5016    │
│ 2018-07-31 ┆ 22:00 ┆ Tuesday ┆ YUS/BD/SHEPPARD SUBWAY ┆ … ┆ 0       ┆ null  ┆ YU/BD ┆ 0       │
│ 2018-07-31 ┆ 23:25 ┆ Tuesday ┆ YONGE BD STATION       ┆ … ┆ 8       ┆ E     ┆ BD    ┆ 5293    │
│ 2018-07-31 ┆ 23:26 ┆ Tuesday ┆ YONGE BD STATION       ┆ … ┆ 8       ┆ W     ┆ BD    ┆ 5092    │
└────────────┴───────┴─────────┴────────────────────────┴───┴─────────┴───────┴───────┴─────────┘, shape: (1_937, 10)
┌────────────┬───────┬───────────┬────────────────────────┬───┬─────────┬───────┬───────┬─────────┐
│ Date       ┆ Time  ┆ Day       ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line  ┆ Vehicle │
│ ---        ┆ ---   ┆ ---       ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---     │
│ date       ┆ str   ┆ str       ┆ str                    ┆   ┆ i64     ┆ str   ┆ str   ┆ i64     │
╞════════════╪═══════╪═══════════╪════════════════════════╪═══╪═════════╪═══════╪═══════╪═════════╡
│ 2018-08-01 ┆ 00:39 ┆ Wednesday ┆ SHEPPARD WEST STATION  ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ 2018-08-01 ┆ 01:30 ┆ Wednesday ┆ MUSEUM STATION         ┆ … ┆ 7       ┆ N     ┆ YU    ┆ 5591    │
│ 2018-08-01 ┆ 02:16 ┆ Wednesday ┆ GREENWOOD WYE          ┆ … ┆ 0       ┆ E     ┆ BD    ┆ 5186    │
│ 2018-08-01 ┆ 04:00 ┆ Wednesday ┆ BLOOR DANFORTH SUBWAY  ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
│ 2018-08-01 ┆ 04:00 ┆ Wednesday ┆ YONGE UNIVERSITY LINE  ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ …          ┆ …     ┆ …         ┆ …                      ┆ … ┆ …       ┆ …     ┆ …     ┆ …       │
│ 2018-08-31 ┆ 22:00 ┆ Friday    ┆ YUS/BD/SHEPPARD SUBWAY ┆ … ┆ 0       ┆ null  ┆ YU/BD ┆ 0       │
│ 2018-08-31 ┆ 22:20 ┆ Friday    ┆ YUS/BD/SHEPPARD SUBWAY ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ 2018-08-31 ┆ 22:48 ┆ Friday    ┆ YONGE BD STATION       ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
│ 2018-08-31 ┆ 23:09 ┆ Friday    ┆ SUMMERHILL STATION     ┆ … ┆ 13      ┆ S     ┆ YU    ┆ 5556    │
│ 2018-08-31 ┆ 23:26 ┆ Friday    ┆ VAUGHAN MC STATION     ┆ … ┆ 10      ┆ S     ┆ YU    ┆ 5681    │
└────────────┴───────┴───────────┴────────────────────────┴───┴─────────┴───────┴───────┴─────────┘, shape: (1_794, 10)
┌────────────┬───────┬──────────┬────────────────────────┬───┬─────────┬───────┬───────┬─────────┐
│ Date       ┆ Time  ┆ Day      ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line  ┆ Vehicle │
│ ---        ┆ ---   ┆ ---      ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---     │
│ date       ┆ str   ┆ str      ┆ str                    ┆   ┆ i64     ┆ str   ┆ str   ┆ i64     │
╞════════════╪═══════╪══════════╪════════════════════════╪═══╪═════════╪═══════╪═══════╪═════════╡
│ 2018-09-01 ┆ 00:22 ┆ Saturday ┆ PAPE STATION           ┆ … ┆ 18      ┆ E     ┆ BD    ┆ 5325    │
│ 2018-09-01 ┆ 00:24 ┆ Saturday ┆ ROYAL YORK STATION     ┆ … ┆ 10      ┆ W     ┆ BD    ┆ 5366    │
│ 2018-09-01 ┆ 00:51 ┆ Saturday ┆ FINCH STATION          ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ 2018-09-01 ┆ 04:00 ┆ Saturday ┆ BLOOR DANFORTH SUBWAY  ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
│ 2018-09-01 ┆ 05:40 ┆ Saturday ┆ GLENCAIRN STATION      ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ …          ┆ …     ┆ …        ┆ …                      ┆ … ┆ …       ┆ …     ┆ …     ┆ …       │
│ 2018-09-30 ┆ 21:46 ┆ Sunday   ┆ VAUGHAN MC STATION     ┆ … ┆ 10      ┆ S     ┆ YU    ┆ 6126    │
│ 2018-09-30 ┆ 22:00 ┆ Sunday   ┆ YUS/BD/SHEPPARD SUBWAY ┆ … ┆ 0       ┆ null  ┆ YU/BD ┆ 0       │
│ 2018-09-30 ┆ 22:10 ┆ Sunday   ┆ VICTORIA PARK STATION  ┆ … ┆ 0       ┆ W     ┆ BD    ┆ 5112    │
│ 2018-09-30 ┆ 22:14 ┆ Sunday   ┆ BLOOR DANFORTH SUBWAY  ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
│ 2018-09-30 ┆ 23:08 ┆ Sunday   ┆ SHEPPARD WEST STATION  ┆ … ┆ 13      ┆ N     ┆ YU    ┆ 5886    │
└────────────┴───────┴──────────┴────────────────────────┴───┴─────────┴───────┴───────┴─────────┘, shape: (1_802, 10)
┌────────────┬───────┬───────────┬───────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time  ┆ Day       ┆ Station               ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---   ┆ ---       ┆ ---                   ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ str   ┆ str       ┆ str                   ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪═══════╪═══════════╪═══════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2018-10-01 ┆ 00:03 ┆ Monday    ┆ EGLINTON STATION      ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 6106    │
│ 2018-10-01 ┆ 00:09 ┆ Monday    ┆ SHERBOURNE STATION    ┆ … ┆ 0       ┆ E     ┆ BD   ┆ 5324    │
│ 2018-10-01 ┆ 01:11 ┆ Monday    ┆ ST GEORGE YUS STATION ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5766    │
│ 2018-10-01 ┆ 01:18 ┆ Monday    ┆ BLOOR STATION         ┆ … ┆ 11      ┆ S     ┆ YU   ┆ 5741    │
│ 2018-10-01 ┆ 01:20 ┆ Monday    ┆ WILSON YARD           ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5986    │
│ …          ┆ …     ┆ …         ┆ …                     ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2018-10-31 ┆ 23:00 ┆ Wednesday ┆ YONGE UNIVERSITY LINE ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2018-10-31 ┆ 23:17 ┆ Wednesday ┆ COXWELL STATION       ┆ … ┆ 9       ┆ E     ┆ BD   ┆ 5117    │
│ 2018-10-31 ┆ 23:21 ┆ Wednesday ┆ GREENWOOD STATION     ┆ … ┆ 7       ┆ E     ┆ BD   ┆ 5061    │
│ 2018-10-31 ┆ 23:40 ┆ Wednesday ┆ BLOOR DANFORTH SUBWAY ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ 2018-10-31 ┆ 23:44 ┆ Wednesday ┆ MAIN STREET STATION   ┆ … ┆ 0       ┆ E     ┆ BD   ┆ 5068    │
└────────────┴───────┴───────────┴───────────────────────┴───┴─────────┴───────┴──────┴─────────┘, shape: (1_738, 10)
┌────────────┬───────┬──────────┬───────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time  ┆ Day      ┆ Station               ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---   ┆ ---      ┆ ---                   ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ str   ┆ str      ┆ str                   ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪═══════╪══════════╪═══════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2018-11-01 ┆ 00:23 ┆ Thursday ┆ KING STATION          ┆ … ┆ 11      ┆ N     ┆ YU   ┆ 5715    │
│ 2018-11-01 ┆ 01:11 ┆ Thursday ┆ COLLEGE STATION       ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 0       │
│ 2018-11-01 ┆ 04:58 ┆ Thursday ┆ YORK MILLS STATION    ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5711    │
│ 2018-11-01 ┆ 05:50 ┆ Thursday ┆ FINCH STATION         ┆ … ┆ 7       ┆ S     ┆ YU   ┆ 6076    │
│ 2018-11-01 ┆ 07:16 ┆ Thursday ┆ ST GEORGE BD STATION  ┆ … ┆ 0       ┆ E     ┆ BD   ┆ 0       │
│ …          ┆ …     ┆ …        ┆ …                     ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2018-11-30 ┆ 22:48 ┆ Friday   ┆ DUNDAS WEST STATION   ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 0       │
│ 2018-11-30 ┆ 23:16 ┆ Friday   ┆ KEELE STATION         ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 0       │
│ 2018-11-30 ┆ 23:30 ┆ Friday   ┆ BLOOR DANFORTH SUBWAY ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ 2018-11-30 ┆ 23:30 ┆ Friday   ┆ DUNDAS STATION        ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 0       │
│ 2018-11-30 ┆ 23:31 ┆ Friday   ┆ EGLINTON STATION      ┆ … ┆ 9       ┆ N     ┆ YU   ┆ 5781    │
└────────────┴───────┴──────────┴───────────────────────┴───┴─────────┴───────┴──────┴─────────┘, shape: (1_465, 10)
┌────────────┬───────┬──────────┬──────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time  ┆ Day      ┆ Station              ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---   ┆ ---      ┆ ---                  ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ str   ┆ str      ┆ str                  ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪═══════╪══════════╪══════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2018-12-01 ┆ 00:11 ┆ Saturday ┆ YONGE BD STATION     ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ 2018-12-01 ┆ 01:13 ┆ Saturday ┆ DUNDAS WEST STATION  ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 5339    │
│ 2018-12-01 ┆ 01:35 ┆ Saturday ┆ SHEPPARD STATION     ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5651    │
│ 2018-12-01 ┆ 01:46 ┆ Saturday ┆ DUNDAS WEST STATION  ┆ … ┆ 8       ┆ W     ┆ BD   ┆ 5339    │
│ 2018-12-01 ┆ 01:51 ┆ Saturday ┆ WOODBINE STATION     ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 0       │
│ …          ┆ …     ┆ …        ┆ …                    ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2018-12-31 ┆ 22:34 ┆ Monday   ┆ DUNDAS STATION       ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2018-12-31 ┆ 22:36 ┆ Monday   ┆ DUNDAS STATION       ┆ … ┆ 6       ┆ N     ┆ YU   ┆ 5881    │
│ 2018-12-31 ┆ 23:08 ┆ Monday   ┆ BLOOR STATION        ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │

In [58]:
check_months_columns(sheets_dict_19)
check_months_columns(sheets_dict_18)

all columns match
all columns match

In [60]:
df_2019 = pl.concat(list(sheets_dict_19.values()))
df_2019

shape: (19_222, 10)
┌────────────┬───────┬─────────┬───────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time  ┆ Day     ┆ Station               ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---   ┆ ---     ┆ ---                   ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ str   ┆ str     ┆ str                   ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪═══════╪═════════╪═══════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2019-01-01 ┆ 01:08 ┆ Tuesday ┆ YORK MILLS STATION    ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 5766    │
│ 2019-01-01 ┆ 02:14 ┆ Tuesday ┆ ST ANDREW STATION     ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2019-01-01 ┆ 02:16 ┆ Tuesday ┆ JANE STATION          ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 5117    │
│ 2019-01-01 ┆ 02:27 ┆ Tuesday ┆ BLOOR STATION         ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5436    │
│ 2019-01-01 ┆ 03:03 ┆ Tuesday ┆ DUPONT STATION        ┆ … ┆ 16      ┆ N     ┆ YU   ┆ 6061    │
│ …          ┆ …     ┆ …       ┆ …                     ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2019-12-31 ┆ 22:54 ┆ Tuesday ┆ FINCH STATION         ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2019-12-31 ┆ 23:09 ┆ Tuesday ┆ SHERBOURNE STATION    ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 5234    │
│ 2019-12-31 ┆ 23:12 ┆ Tuesday ┆ ST CLAIR WEST STATION ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2019-12-31 ┆ 23:16 ┆ Tuesday ┆ FINCH STATION         ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 6066    │
│ 2019-12-31 ┆ 23:32 ┆ Tuesday ┆ KING STATION          ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 0       │
└────────────┴───────┴─────────┴───────────────────────┴───┴─────────┴───────┴──────┴─────────┘

In [61]:
df_2019 = df_2019.with_columns(
    pl.col("Time").str.to_time("%H:%M")
)
df_2019

shape: (19_222, 10)
┌────────────┬──────────┬─────────┬───────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time     ┆ Day     ┆ Station               ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---      ┆ ---     ┆ ---                   ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ time     ┆ str     ┆ str                   ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪══════════╪═════════╪═══════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2019-01-01 ┆ 01:08:00 ┆ Tuesday ┆ YORK MILLS STATION    ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 5766    │
│ 2019-01-01 ┆ 02:14:00 ┆ Tuesday ┆ ST ANDREW STATION     ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2019-01-01 ┆ 02:16:00 ┆ Tuesday ┆ JANE STATION          ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 5117    │
│ 2019-01-01 ┆ 02:27:00 ┆ Tuesday ┆ BLOOR STATION         ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5436    │
│ 2019-01-01 ┆ 03:03:00 ┆ Tuesday ┆ DUPONT STATION        ┆ … ┆ 16      ┆ N     ┆ YU   ┆ 6061    │
│ …          ┆ …        ┆ …       ┆ …                     ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2019-12-31 ┆ 22:54:00 ┆ Tuesday ┆ FINCH STATION         ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2019-12-31 ┆ 23:09:00 ┆ Tuesday ┆ SHERBOURNE STATION    ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 5234    │
│ 2019-12-31 ┆ 23:12:00 ┆ Tuesday ┆ ST CLAIR WEST STATION ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2019-12-31 ┆ 23:16:00 ┆ Tuesday ┆ FINCH STATION         ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 6066    │
│ 2019-12-31 ┆ 23:32:00 ┆ Tuesday ┆ KING STATION          ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 0       │
└────────────┴──────────┴─────────┴───────────────────────┴───┴─────────┴───────┴──────┴─────────┘

In [62]:
df_2018 = pl.concat(list(sheets_dict_18.values()))
df_2018

shape: (20_737, 10)
┌────────────┬───────┬────────┬───────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time  ┆ Day    ┆ Station               ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---   ┆ ---    ┆ ---                   ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ str   ┆ str    ┆ str                   ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪═══════╪════════╪═══════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2018-01-01 ┆ 00:29 ┆ Monday ┆ SHEPPARD WEST STATION ┆ … ┆ 15      ┆ N     ┆ YU   ┆ 5986    │
│ 2018-01-01 ┆ 01:07 ┆ Monday ┆ DUNDAS STATION        ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2018-01-01 ┆ 01:22 ┆ Monday ┆ MUSEUM STATION        ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5751    │
│ 2018-01-01 ┆ 01:28 ┆ Monday ┆ BAY LOWER             ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 5222    │
│ 2018-01-01 ┆ 01:39 ┆ Monday ┆ MUSEUM STATION        ┆ … ┆ 11      ┆ S     ┆ YU   ┆ 5781    │
│ …          ┆ …     ┆ …      ┆ …                     ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2018-12-31 ┆ 22:34 ┆ Monday ┆ DUNDAS STATION        ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2018-12-31 ┆ 22:36 ┆ Monday ┆ DUNDAS STATION        ┆ … ┆ 6       ┆ N     ┆ YU   ┆ 5881    │
│ 2018-12-31 ┆ 23:08 ┆ Monday ┆ BLOOR STATION         ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2018-12-31 ┆ 23:21 ┆ Monday ┆ QUEEN'S PARK STATION  ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 5841    │
│ 2018-12-31 ┆ 23:32 ┆ Monday ┆ ST CLAIR STATION      ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 6061    │
└────────────┴───────┴────────┴───────────────────────┴───┴─────────┴───────┴──────┴─────────┘

In [63]:
df_2018 = df_2018.with_columns(
    pl.col("Time").str.to_time("%H:%M")
)
df_2018

shape: (20_737, 10)
┌────────────┬──────────┬────────┬───────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time     ┆ Day    ┆ Station               ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---      ┆ ---    ┆ ---                   ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ time     ┆ str    ┆ str                   ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪══════════╪════════╪═══════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2018-01-01 ┆ 00:29:00 ┆ Monday ┆ SHEPPARD WEST STATION ┆ … ┆ 15      ┆ N     ┆ YU   ┆ 5986    │
│ 2018-01-01 ┆ 01:07:00 ┆ Monday ┆ DUNDAS STATION        ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2018-01-01 ┆ 01:22:00 ┆ Monday ┆ MUSEUM STATION        ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5751    │
│ 2018-01-01 ┆ 01:28:00 ┆ Monday ┆ BAY LOWER             ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 5222    │
│ 2018-01-01 ┆ 01:39:00 ┆ Monday ┆ MUSEUM STATION        ┆ … ┆ 11      ┆ S     ┆ YU   ┆ 5781    │
│ …          ┆ …        ┆ …      ┆ …                     ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2018-12-31 ┆ 22:34:00 ┆ Monday ┆ DUNDAS STATION        ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2018-12-31 ┆ 22:36:00 ┆ Monday ┆ DUNDAS STATION        ┆ … ┆ 6       ┆ N     ┆ YU   ┆ 5881    │
│ 2018-12-31 ┆ 23:08:00 ┆ Monday ┆ BLOOR STATION         ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2018-12-31 ┆ 23:21:00 ┆ Monday ┆ QUEEN'S PARK STATION  ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 5841    │
│ 2018-12-31 ┆ 23:32:00 ┆ Monday ┆ ST CLAIR STATION      ┆ … ┆ 0       ┆ S     ┆ YU   ┆ 6061    │
└────────────┴──────────┴────────┴───────────────────────┴───┴─────────┴───────┴──────┴─────────┘

In [64]:
df_since_18 = pl.concat([df_2018, df_2019, df_since_20])
df_since_18

shape: (181_078, 10)
┌────────────┬──────────┬─────────┬────────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time     ┆ Day     ┆ Station                ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---      ┆ ---     ┆ ---                    ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ time     ┆ str     ┆ str                    ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪══════════╪═════════╪════════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2018-01-01 ┆ 00:29:00 ┆ Monday  ┆ SHEPPARD WEST STATION  ┆ … ┆ 15      ┆ N     ┆ YU   ┆ 5986    │
│ 2018-01-01 ┆ 01:07:00 ┆ Monday  ┆ DUNDAS STATION         ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2018-01-01 ┆ 01:22:00 ┆ Monday  ┆ MUSEUM STATION         ┆ … ┆ 0       ┆ N     ┆ YU   ┆ 5751    │
│ 2018-01-01 ┆ 01:28:00 ┆ Monday  ┆ BAY LOWER              ┆ … ┆ 0       ┆ null  ┆ BD   ┆ 5222    │
│ 2018-01-01 ┆ 01:39:00 ┆ Monday  ┆ MUSEUM STATION         ┆ … ┆ 11      ┆ S     ┆ YU   ┆ 5781    │
│ …          ┆ …        ┆ …       ┆ …                      ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2026-06-30 ┆ 01:37:00 ┆ Tuesday ┆ KENNEDY BD STATION     ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 0       │
│ 2026-06-30 ┆ 17:57:00 ┆ Tuesday ┆ SHEPPARD-YONGE STATION ┆ … ┆ 0       ┆ W     ┆ SHP  ┆ 6191    │
│ 2026-06-30 ┆ 18:53:00 ┆ Tuesday ┆ DON MILLS STATION      ┆ … ┆ 0       ┆ null  ┆ SHP  ┆ 0       │
│ 2026-06-30 ┆ 21:04:00 ┆ Tuesday ┆ SHEPPARD-YONGE STATION ┆ … ┆ 0       ┆ E     ┆ SHP  ┆ 6161    │
│ 2026-06-30 ┆ 21:26:00 ┆ Tuesday ┆ SHEPPARD-YONGE STATION ┆ … ┆ 9       ┆ W     ┆ SHP  ┆ 6176    │
└────────────┴──────────┴─────────┴────────────────────────┴───┴─────────┴───────┴──────┴─────────┘

In [65]:
df_from_14_to_17_path = data_dir / "ttc-subway-delay-jan-2014-april-2017.xlsx"
df_from_14_to_17 = pl.read_excel(df_from_14_to_17_path)
df_from_14_to_17

/var/folders/ch/33mzvf3519l1kk_ktmcysmc80000gn/T/ipykernel_81715/3484725089.py:2: FutureWarning: from_arrow(<ArrowStreamExportable>) will return a Series instead of a DataFrame in 2.0. To avoid this warning, pass the ArrowStreamExportable to either `pl.DataFrame` or `pl.Series` instead based on your desired output type.
  df_from_14_to_17 = pl.read_excel(df_from_14_to_17_path)

shape: (69_016, 10)
┌────────────┬───────┬───────────┬───────────────────────┬───┬─────────┬───────┬───────┬─────────┐
│ Date       ┆ Time  ┆ Day       ┆ Station               ┆ … ┆ Min Gap ┆ Bound ┆ Line  ┆ Vehicle │
│ ---        ┆ ---   ┆ ---       ┆ ---                   ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---     │
│ date       ┆ str   ┆ str       ┆ str                   ┆   ┆ i64     ┆ str   ┆ str   ┆ i64     │
╞════════════╪═══════╪═══════════╪═══════════════════════╪═══╪═════════╪═══════╪═══════╪═════════╡
│ 2014-01-01 ┆ 00:21 ┆ Wednesday ┆ VICTORIA PARK STATION ┆ … ┆ 60      ┆ W     ┆ BD    ┆ 5111    │
│ 2014-01-01 ┆ 02:06 ┆ Wednesday ┆ HIGH PARK STATION     ┆ … ┆ 7       ┆ W     ┆ BD    ┆ 5001    │
│ 2014-01-01 ┆ 02:40 ┆ Wednesday ┆ SHEPPARD STATION      ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ 2014-01-01 ┆ 03:10 ┆ Wednesday ┆ LANSDOWNE STATION     ┆ … ┆ 8       ┆ W     ┆ BD    ┆ 5116    │
│ 2014-01-01 ┆ 03:20 ┆ Wednesday ┆ BLOOR STATION         ┆ … ┆ 10      ┆ S     ┆ YU    ┆ 5386    │
│ …          ┆ …     ┆ …         ┆ …                     ┆ … ┆ …       ┆ …     ┆ …     ┆ …       │
│ 2017-04-30 ┆ 19:50 ┆ Sunday    ┆ BLOOR DANFORTH SUBWAY ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
│ 2017-04-30 ┆ 20:25 ┆ Sunday    ┆ WARDEN STATION        ┆ … ┆ 8       ┆ W     ┆ BD    ┆ 5107    │
│ 2017-04-30 ┆ 20:29 ┆ Sunday    ┆ KEELE STATION         ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
│ 2017-04-30 ┆ 22:00 ┆ Sunday    ┆ YONGE UNIVERSITY LINE ┆ … ┆ 0       ┆ null  ┆ YU/BD ┆ 0       │
│ 2017-04-30 ┆ 22:13 ┆ Sunday    ┆ BLOOR DANFORTH SUBWAY ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
└────────────┴───────┴───────────┴───────────────────────┴───┴─────────┴───────┴───────┴─────────┘

In [66]:
df_from_14_to_17 = df_from_14_to_17.with_columns(
    pl.col("Time").str.to_time("%H:%M")
) 
df_from_14_to_17

shape: (69_016, 10)
┌────────────┬──────────┬───────────┬───────────────────┬───┬─────────┬───────┬───────┬─────────┐
│ Date       ┆ Time     ┆ Day       ┆ Station           ┆ … ┆ Min Gap ┆ Bound ┆ Line  ┆ Vehicle │
│ ---        ┆ ---      ┆ ---       ┆ ---               ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---     │
│ date       ┆ time     ┆ str       ┆ str               ┆   ┆ i64     ┆ str   ┆ str   ┆ i64     │
╞════════════╪══════════╪═══════════╪═══════════════════╪═══╪═════════╪═══════╪═══════╪═════════╡
│ 2014-01-01 ┆ 00:21:00 ┆ Wednesday ┆ VICTORIA PARK     ┆ … ┆ 60      ┆ W     ┆ BD    ┆ 5111    │
│            ┆          ┆           ┆ STATION           ┆   ┆         ┆       ┆       ┆         │
│ 2014-01-01 ┆ 02:06:00 ┆ Wednesday ┆ HIGH PARK STATION ┆ … ┆ 7       ┆ W     ┆ BD    ┆ 5001    │
│ 2014-01-01 ┆ 02:40:00 ┆ Wednesday ┆ SHEPPARD STATION  ┆ … ┆ 0       ┆ null  ┆ YU    ┆ 0       │
│ 2014-01-01 ┆ 03:10:00 ┆ Wednesday ┆ LANSDOWNE STATION ┆ … ┆ 8       ┆ W     ┆ BD    ┆ 5116    │
│ 2014-01-01 ┆ 03:20:00 ┆ Wednesday ┆ BLOOR STATION     ┆ … ┆ 10      ┆ S     ┆ YU    ┆ 5386    │
│ …          ┆ …        ┆ …         ┆ …                 ┆ … ┆ …       ┆ …     ┆ …     ┆ …       │
│ 2017-04-30 ┆ 19:50:00 ┆ Sunday    ┆ BLOOR DANFORTH    ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
│            ┆          ┆           ┆ SUBWAY            ┆   ┆         ┆       ┆       ┆         │
│ 2017-04-30 ┆ 20:25:00 ┆ Sunday    ┆ WARDEN STATION    ┆ … ┆ 8       ┆ W     ┆ BD    ┆ 5107    │
│ 2017-04-30 ┆ 20:29:00 ┆ Sunday    ┆ KEELE STATION     ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
│ 2017-04-30 ┆ 22:00:00 ┆ Sunday    ┆ YONGE UNIVERSITY  ┆ … ┆ 0       ┆ null  ┆ YU/BD ┆ 0       │
│            ┆          ┆           ┆ LINE              ┆   ┆         ┆       ┆       ┆         │
│ 2017-04-30 ┆ 22:13:00 ┆ Sunday    ┆ BLOOR DANFORTH    ┆ … ┆ 0       ┆ null  ┆ BD    ┆ 0       │
│            ┆          ┆           ┆ SUBWAY            ┆   ┆         ┆       ┆       ┆         │
└────────────┴──────────┴───────────┴───────────────────┴───┴─────────┴───────┴───────┴─────────┘

In [67]:
df_since_14 = pl.concat([df_from_14_to_17, df_since_18])
df_since_14

shape: (250_094, 10)
┌────────────┬──────────┬───────────┬───────────────────────┬───┬─────────┬───────┬──────┬─────────┐
│ Date       ┆ Time     ┆ Day       ┆ Station               ┆ … ┆ Min Gap ┆ Bound ┆ Line ┆ Vehicle │
│ ---        ┆ ---      ┆ ---       ┆ ---                   ┆   ┆ ---     ┆ ---   ┆ ---  ┆ ---     │
│ date       ┆ time     ┆ str       ┆ str                   ┆   ┆ i64     ┆ str   ┆ str  ┆ i64     │
╞════════════╪══════════╪═══════════╪═══════════════════════╪═══╪═════════╪═══════╪══════╪═════════╡
│ 2014-01-01 ┆ 00:21:00 ┆ Wednesday ┆ VICTORIA PARK STATION ┆ … ┆ 60      ┆ W     ┆ BD   ┆ 5111    │
│ 2014-01-01 ┆ 02:06:00 ┆ Wednesday ┆ HIGH PARK STATION     ┆ … ┆ 7       ┆ W     ┆ BD   ┆ 5001    │
│ 2014-01-01 ┆ 02:40:00 ┆ Wednesday ┆ SHEPPARD STATION      ┆ … ┆ 0       ┆ null  ┆ YU   ┆ 0       │
│ 2014-01-01 ┆ 03:10:00 ┆ Wednesday ┆ LANSDOWNE STATION     ┆ … ┆ 8       ┆ W     ┆ BD   ┆ 5116    │
│ 2014-01-01 ┆ 03:20:00 ┆ Wednesday ┆ BLOOR STATION         ┆ … ┆ 10      ┆ S     ┆ YU   ┆ 5386    │
│ …          ┆ …        ┆ …         ┆ …                     ┆ … ┆ …       ┆ …     ┆ …    ┆ …       │
│ 2026-06-30 ┆ 01:37:00 ┆ Tuesday   ┆ KENNEDY BD STATION    ┆ … ┆ 0       ┆ W     ┆ BD   ┆ 0       │
│ 2026-06-30 ┆ 17:57:00 ┆ Tuesday   ┆ SHEPPARD-YONGE        ┆ … ┆ 0       ┆ W     ┆ SHP  ┆ 6191    │
│            ┆          ┆           ┆ STATION               ┆   ┆         ┆       ┆      ┆         │
│ 2026-06-30 ┆ 18:53:00 ┆ Tuesday   ┆ DON MILLS STATION     ┆ … ┆ 0       ┆ null  ┆ SHP  ┆ 0       │
│ 2026-06-30 ┆ 21:04:00 ┆ Tuesday   ┆ SHEPPARD-YONGE        ┆ … ┆ 0       ┆ E     ┆ SHP  ┆ 6161    │
│            ┆          ┆           ┆ STATION               ┆   ┆         ┆       ┆      ┆         │
│ 2026-06-30 ┆ 21:26:00 ┆ Tuesday   ┆ SHEPPARD-YONGE        ┆ … ┆ 9       ┆ W     ┆ SHP  ┆ 6176    │
│            ┆          ┆           ┆ STATION               ┆   ┆         ┆       ┆      ┆         │
└────────────┴──────────┴───────────┴───────────────────────┴───┴─────────┴───────┴──────┴─────────┘